### ISSUE TITLE
BUG:`read_file` removes UTC offset from datetime fields when reading GeoJSON

### ISSUE THREAD

**Issue by EigenJT** [geopandas/geopandas#1472] opened 2020-06-16 02:31 UTC
It looks like `geopandas.read_file` removes timezone information from an ISO 8601 (YYYY-MM-DDTHH-MM-SS+HH:MM or YYYY-MM-DDTHH-MM-SSZ) datetime string when reading from a GeoJSON file.

Example: The datetime in the following geojson
```
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": {"datetime": "2015-04-22T00:00:00+07:00" }, 
"geometry": { "type": "Point", "coordinates": [ -79.4, 43.6 ] } }
]
}
```
ends up looking like
```python
test = geopandas.read_file("test_file.geojson")
test[["datetime","geometry"]].iloc[0]
datetime           2015-04-22T00:00:00
geometry            POINT (-79.4, 43.6 )
Name: 0, dtype: object
```
When the column is not all ISO formatted strings, for example:
```
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": {"datetime": "2015-04-22T00:00:00+07:00" }, 
"geometry": { "type": "Point", "coordinates": [ -79.4, 43.6 ] } },
{ "type": "Feature", "properties": {"datetime": "hello_world" }, 
"geometry": { "type": "Point", "coordinates": [ -79.5, 43.2 ] } }
]
}
```
then we get
```python
            Last_Update_Date                    geometry
0                hello_world  POINT (-79.4, 43.6)
1  2018-09-07T00:00:00+00:00  POINT (-79.5, 43.2)
```
Could this be some hidden datetime parsing coming from `fiona` or `pandas`?

Adding keywords like:
```python
parse_dates = False
infer_datetime_format = False
convert_dates = False
```
doesn't have any effect. It also seems like it's not just a displaying error, as the actual values are now timezone-naive datetime strings.

Possibly has to do with: [https://github.com/pandas-dev/pandas/pull/33133](https://github.com/pandas-dev/pandas/pull/33133)

**Comment by jorisvandenbossche** [comment] 2020-06-16 06:33
It seems the cause lies in fiona (or GDAL), since when iterating with fiona, the timezone is lost:

```
In [1]: %%writefile test_datetime.geojson 
   ...: { 
   ...: "type": "FeatureCollection", 
   ...: "features": [ 
   ...: { "type": "Feature", "properties": {"datetime": "2015-04-22T00:00:00+07:00" },  
   ...: "geometry": { "type": "Point", "coordinates": [ -79.4, 43.6 ] } } 
   ...: ] 
   ...: } 
Writing test_datetime.geojson

In [2]: import fiona 

In [3]: col = fiona.open("test_datetime.geojson")  

In [5]: next(col.filter())    
Out[5]: 
{'type': 'Feature',
 'id': '0',
 'properties': OrderedDict([('datetime', '2015-04-22T00:00:00')]),
 'geometry': {'type': 'Point', 'coordinates': (-79.4, 43.6)}}
```

So geopandas receives the data as shown above, which has the datetime as a string, but without the timezone. 

I am not sure what the general level of support is for timezones in GDAL/fiona.

**Comment by EigenJT** [comment] 2020-06-24 00:40
UPDATE:
Seems like the Fiona maintainers are working on a fix: [https://github.com/Toblerity/Fiona/pull/915](https://github.com/Toblerity/Fiona/pull/915)

**Comment by martinfleis** [comment] 2020-07-01 20:11
Closing as it is being fixed in `Fiona`.

**Closed by martinfleis** 2020-07-01 20:11 UTC
