### ISSUE TITLE
REGR: performance degrading after updating from version 0.8.2 to 0.9, using the "overlay"-method

### ISSUE THREAD

**Issue by Schulz3** [geopandas/geopandas#2089] opened 2021-08-28 21:35 UTC
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

Hello! The OS I'm working on is Microsoft Windows 10 LTSC. I often need to split GeoDataFrames with a minimum number of 350.000 Points into approximately 100 Polygons with:
```
cell_points = gpd.overlay(gdf_points, gdf_polygons, how='intersection')
```
So I was very happy when I found this bug report on the geopandas GitHub site: https://github.com/geopandas/geopandas/issues/1793. A bit further down in the thread, I found that geopandas 0.8.2 was released which works with pygeos. After I had updated from 0.8.1 to 0.8.2 my code executed much much faster. But when I recently updated to version 0.9, I quickly noticed that my code executed much much slower. Luckily, switching back to version 0.8.2 brought back the execution improvement.
What I did was to set up a virtual environment. Then I installed first of all geopandas from conda-forge, then I installed pygeos from conda-forge. This is the code that I used to measure the time:
```
import geopandas as gpd
import numpy as np
import pandas as pd
from shapely.geometry import Polygon
from time import perf_counter


print(gpd.__version__)


def create_Polygon(row):
   return Polygon([(i[0], i[1]) for i in row.reshape((4, 2))])


# #### Generate random Points inside (0, 10) ######
df_points = pd.DataFrame(data=np.random.rand(100000, 2) * 10, columns=['X', 'Y'])
gdf_points = gpd.GeoDataFrame(df_points, geometry=gpd.points_from_xy(df_points['X'], df_points['Y']))

# #### Generate 100 Polygons (Squares with edge length of 1) inside (0, 10) #####
step = 1
arr = np.zeros(shape=(100, 8))
counter = 0
for i in range(10):
   for j in range(10):
       arr[counter] = [i, j, i+step, j, i+step, j+step, i, j+step]
       counter += 1
gdf_polygons = gpd.GeoDataFrame(data=list(range(100)),
                               geometry=np.apply_along_axis(create_Polygon, axis=1, arr=arr))

# #### Intersect Polygons with Points #####
time_start = perf_counter()
cell_points = gpd.overlay(gdf_points, gdf_polygons, how='intersection')
print(f'Time: {(perf_counter() - time_start):.2f} seconds')
```
The execution time of version 0.9 was approximately 40 seconds. The execution time of version 0.8.2 was approximately 0.6 seconds! (Both with Python version 3.9.6, executed in PyCharm). My question is: Can someone recreate this? Is there maybe something else that I should have installed, when updating to geopandas version 0.9 to keep the performance improvements from version 0.8.2?

**Comment by martinfleis** [comment] 2021-09-02 20:51
Wow, that is quite a performance hit.

I can confirm it in my environment. The issue comes from `keep_geom_type=True` option that checks geometry types but in a very sloppy way. 99% of the time is spent on `dissolve` in that check. If you pass `keep_geom_type=False` to overlay, you're back at 0.6s.

https://github.com/geopandas/geopandas/blob/8f08539b3f472c84daac52a847984584c63731db/geopandas/tools/overlay.py#L337

It was implemented in #1582 (cc @jdmcbr) and released in 0.9.0. I would say this can even be considered a regression that should be fixed before we release 0.10.

Thanks a lot for the report!

**Comment by jdmcbr** [comment] 2021-09-03 00:27
Oh gosh, that's terrible, sorry @Schulz3.

@martinfleis your response suggests you might already have an idea of a better way to perform this check without incurring the performance penalty? I admittedly am not immediately seeing a clearly more performant way to do this check, but can start looking for one if there wasn't something you already had in mind.

**Comment by martinfleis** [comment] 2021-09-03 07:43
No, I haven't thought about that. What is clear is that dissolve is not the way.

**Comment by TLouf** [comment] 2021-09-03 10:32
The bottleneck is this groupby's aggregation in `dissolve`:

https://github.com/geopandas/geopandas/blob/8f08539b3f472c84daac52a847984584c63731db/geopandas/geodataframe.py#L1525-L1535

which initialises a `GeoSeries` for each block. I've removed the aggregation and iterated over the groupby's indices to select the geometries from the `GeometryArray` direclty, apply `unary_union` and append the resulting geometry to a list. With this list I can then initialise `aggregated_geometry`. I get a 3x performance improvement this way. This whole generation of `aggregated_geometry` can also be skipped if all groups are singletons, and thus recover more or less the original performance.

Shall I go ahead with a PR?

**Comment by martinfleis** [comment] 2021-09-03 10:40
@TLouf That gives a performance improvement for any `dissolve` operation, right? If so, PR is welcome. 

I don't think it solves this regression though since we are  60x slower than before. 3x speedup will make it _"only"_ 20x slower :). I think we need to find another way here since `unary_union` will always be expensive.

**Comment by TLouf** [comment] 2021-09-03 10:49
Well in this case here the whole `dissolve` can be skipped because no geometry is actually exploded, we're only doing unary_unions of single geometries. Actually I didn't think of it when I tested but in `dissolve` the unary_union part can be skipped for singletons too. The function is still costly because I need to initialise a `GeometryArray` from a list of geometries, and `__getitem__` many times though.

**Comment by martinfleis** [comment] 2021-09-03 13:39
I think that the way forward here could be 

1. filter out results of a different geom type
2. filter geometry collections, loop through the collection and remove different types

that should do the trick while avoiding unions and tackling only those geometries that need to be altered.

**Comment by jorisvandenbossche** [comment] 2021-09-08 10:59
On the actual issue of `overlay` needing to call (or not) the `dissolve` method or not: what's is it used for? 
So looking at the code and the PR that added it, we are doing 1) an explode, 2) filter out unwanted geometry types, and 3) dissolve again to reverse the explode.  

But AFAIU this was specifically done for GeometryCollections, and not for other Multi goemetries (eg if you have a MultiPolygon in the result, exploding it would give polygons, which won't be filtered out if a MultiPolygon is fine, and dissolving those polygons will give back the original MultiPolygon). 
So first, we should probably only do this explode/dissolve sequence in case there are actually geometry collections present (I suppose checking for this is relatively cheap compared to the actual overlay operation). And second, we also don't really need a "dissolve" (using `unary_union`) while we actually know that we just want to create a GeometryCollection. 
(reading Martin's post above again, so that's basically the same as what Martin already said .. :)).

One option could be to first filter out the geometry collections as a subset, and only do the exploding/filtering/recombining on this subset, and then assign the resulting filtered collections to the full geometry array. With `pygeos.geometrycollections` you can actually create GeometryCollections based on indices you get from exploding. So that could be used instead of dissolve/unary_union to recreate the collections.

**Closed** 2021-09-25 15:19 UTC
Labels: performance, regression
