### ISSUE TITLE
big integer i/o handling

### ISSUE THREAD

**Issue by gboeing** [geopandas/geopandas#691] opened 2018-03-16 18:45 UTC
If I create a GeoDataFrame like this:

```python
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
d = {'id' : [3694063472, 3694063473],
     'geometry' : [Point((-122.278015,37.868995)),
                   Point((-122.278876,37.868895))]}
gdf = gpd.GeoDataFrame(d)
gdf
```
Returns:
```
			     geometry	        id
0	POINT (-122.278015 37.868995)	3694063472
1	POINT (-122.278876 37.868895)	3694063473
```

If I save to csv as a pandas Dataframe and read it back in:

```python
pd.DataFrame(gdf).to_csv('test.csv', index=False)
pd.read_csv('test.csv')
```
Returns:
```
			     geometry	        id
0	POINT (-122.278015 37.868995)	3694063472
1	POINT (-122.278876 37.868895)	3694063473
```

Everything's the same. But if I save to disk as a shapefile:

```python
gdf.to_file('test_shp')
gpd.read_file('test_shp')
```
Returns:
```
	        id			     geometry
0	2147483647	POINT (-122.278015 37.868995)
1	2147483647	POINT (-122.278876 37.868895)
```

Writing my GeoDataFrame to disk and reading it back in results in my id field's values silently being changed to 2147483647, the max value for a 32-bit signed integer. This is in geopandas 0.3.0 with fiona 1.7.11.

**Comment by jorisvandenbossche** [comment] 2018-03-16 23:52
Thanks for the report! 
This seems to be a bug in out schema inferring:

```
In [20]: geopandas.io.file.infer_schema(gdf)
Out[20]: {'geometry': 'Point', 'properties': OrderedDict([('id', 'int')])}
```

and if the field width is not specified, 'int' is considered to be 9 chars wide (http://www.gdal.org/drv_shapefile.html), while we have 10 in this case. 

Manually specifying the schema with appropriate schema shows that this can fix the issue:
```
In [21]: from collections import OrderedDict

In [23]: schema= {'geometry': 'Point', 'properties': OrderedDict([('id', 'int:10')])}

In [24]: gdf.to_file('test_shp', schema=schema)

In [25]: gpd.read_file('test_shp')
Out[25]: 
           id                       geometry
0  3694063472  POINT (-122.278015 37.868995)
1  3694063473  POINT (-122.278876 37.868895)
```

@sgillies is there some helper functionality in `fiona` to determine widths / inferring schema's ?

Currently we only return 'str', 'int' or 'float', and never specific field width:

https://github.com/geopandas/geopandas/blob/8d39811b822db9e13f8876c595952b07681892d6/geopandas/io/file.py#L120-L130

**Comment by sgillies** [comment] 2018-03-24 03:34
@jorisvandenbossche sorry to be slow to reply to this! I've confirmed the issue. At first, I blamed the shapefile format, but it also manifests with a GeoPackage in my tests and must therefore be a Fiona issue.

As you note, specifying `int:n` where n>=10 is the workaround. I'm going to dig into this during the weekend and will follow up here soon.

**Comment by sgillies** [comment] 2018-03-28 17:37
@jorisvandenbossche I've got a solution (for Fiona 1.8) coming up. Meanwhile, I suggest this mapping of Python/Numpy types to Fiona/GDAL types:

```
Python/Numpy : Fiona/GDAL
-------------------------
int, int64, long : 'int:18'
int32 : 'int:9'
bool : 'bool' 
```

**Comment by rutgerhofste** [comment] 2018-06-21 10:20
Just encountered the same issue. Thanks for working on a fix. Any idea when this will be implemented?

**Comment by jdmcbr** [comment] 2018-08-04 21:10
This is fixed on fiona master now.

```
In [1]: gdf = gpd.read_file(gpd.datasets.get_path("nybb"))

In [2]: gdf["big_int"] = arange(5) + 12345678910

In [3]: gdf.to_file("test.shp")

In [4]: gdf_back = gpd.read_file("test.shp")

In [5]: gdf_back["big_int"]
Out[5]: 
0    12345678910
1    12345678911
2    12345678912
3    12345678913
4    12345678914
Name: big_int, dtype: int64
```

**Closed by jdmcbr** 2018-08-04 21:10 UTC

**Comment by jorisvandenbossche** [comment] 2018-08-16 13:47
@sgillies thanks for fixing this!

A late question regarding your comment above (https://github.com/geopandas/geopandas/issues/691#issuecomment-376972182). 
You mention that python/numpy `bool` dtypes should be mapped to 'bool' fiona/gdal type. But I was under the impression that bool was not supported, at least we error for that in the current code in geopandas:

https://github.com/geopandas/geopandas/blob/b2dd9f28e9bd7fefee98f225d31769835c5b8bf3/geopandas/io/file.py#L126-L129

Is this now supported?

Also, is the distinction between `'int:18'` and `'int:9'` also needed with the latest version of fiona? (we currently simply infer 'int') Or will fiona do that automatically depending on the data if you pass simply 'int' ?

**Comment by sgillies** [comment] 2018-08-17 08:13
@jorisvandenbossche yes, `bool` will be supported in Fiona 1.8 *with* GDAL 2. GDAL doesn't have a boolean type, but has added subtypes for its integer type so that we can mark fields as being type:integer, subtype:boolean.

The need to make a distinction between `int:18` and `int:9` will go away in Fiona 1.8. Python/numpy `int` (or `int64`) becomes a GDAL 64-bit integer (aka `int:18`). Python/numpy `int32` becomes a GDAL 32-bit integer (aka `int:9`).

**Comment by jorisvandenbossche** [comment] 2018-08-17 08:29
Thanks for the clarifications!

> Python/numpy int (or int64) becomes a GDAL 64-bit integer (aka int:18)

Since we convert numpy scalars to Python ints before passing the data to fiona (in `GeoDataFrame.iterfeatures()`), this means it will always be 'int:18' that fiona infers. So maybe we should still specify in the passed schema 'int:18' vs 'int:9' instead of simply 'int' based on the dtype of the column (np.int64 vs np.int32).

**Comment by sgillies** [comment] 2018-08-17 08:51
> So maybe we should still specify in the passed schema 'int:18' vs 'int:9' instead of simply 'int' based on the dtype of the column (np.int64 vs np.int32).

Yes, this is a good approach and will work with Fiona 1.8.
