### ISSUE TITLE
BUG: up to 4 times slower in Linux compared to Windows when using gpd.read_file to read vector data

### ISSUE THREAD

**Issue by kwtk86** [geopandas/geopandas#3210] opened 2024-03-06 10:09 UTC
It is very very slow to read vector data (including ESRI ShapeFile, ESRI Geodatabase) with gpd.read_file in Linux (Including Ubuntu, Rocky linux). I have reproduced this issue in several different Linux servers with high performace and Windows PCs, so it seemed that it is not a question involving the performace of devices but a question related to GeoPandas or Fiona
For instance, reading a point gdb layer with 100000 points might cost 10 secends in Windows, but it would cost up to 40 seconds to read the same data with gpd.read_file in Linux servers. 
The same problem occurs when reading shp data, but not as severe. Reading with gpd.read_file on linux might only take twice times.

By debugging the Python source code for GeoPandas, I've pinpointed the particularly slow code, which is GeoDataframe.from_features in geodataframe.py. It looks like it is iterating over the return value of fiona.open that is particularly slow. I'm not sure if this is due to geopandas, or fiona?
![image](https://github.com/geopandas/geopandas/assets/63400477/5416aa28-2d82-4614-b1dd-f5f84d0ddc18)

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.3
numpy      : 1.24.3
pandas     : 2.0.1
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.5
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.6.1
pygeos     : None
pyogrio    : 0.6.0
psycopg2   : None
pyarrow    : None
rtree      : 1.1.0
</details>

**Comment by theroggy** [comment] 2024-03-06 19:08
Fiona is indeed known to be rather slow for larger files.

GeoPandas also supports a different IO engine, [pyogrio](https://pyogrio.readthedocs.io), that is optimised for bulk-reading data rather than row-per-row. Just make sure the `pyogrio` package is installed, and add the `engine="pyogrio"` parameter to your [gpd.read_file](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html) call. This should give a significant performance improvement of ~5x up to 20x faster.

If you want some more improvement, you can install the `pyarrow` package as well, and add the `use_arrow=True` parameter to `read_file` in addition to `engine="pyogrio"`. In some situation this gives another similar performance boost.

**Comment by martinfleis** [comment] 2024-03-06 19:33
@theroggy this is all correct but I am not sure why there's such a difference between OS. Have you noticed anything like that as well? If something, I would expect Linux to be faster...

**Comment by martinfleis** [comment] 2024-03-06 20:15
> Luckily it's an mystery that will soon become irrelevant...

Unless it is caused by GDAL and reading with pyogrio shows the same difference.

**Comment by kwtk86** [comment] 2024-03-07 03:57
> Fiona is indeed known to be rather slow for larger files.
> 
> GeoPandas also supports a different IO engine, [Pyogrio](https://pyogrio.readthedocs.io), that is optimised for reading and writing data in bulk rather than row-per-row. Just make sure the `pyogrio` package is installed, and add the `engine="pyogrio"` parameter to your [gpd.read_file](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html) call. This should give a significant performance improvement (~5x up to 20x faster).
> 
> If you want some more improvement, you can install the `pyarrow` package as well, and add the `use_arrow=True` parameter to `read_file` in addition to `engine="pyogrio"`. In most situations this gives another significant performance boost.
> 
> For the next major version of GeoPandas, planned to be released ~next month, it is planned to switch the default IO engine from Fiona to Pyogrio.

Thanks a lot! It became much faster after engine="pyogrio" was added. 
However, I wonder that, now that engine="pyogrio" can accelerate reading files so significantly, why engine="pyogrio"  is not the default option?

**Comment by kwtk86** [comment] 2024-03-07 04:04
> Fiona is indeed known to be rather slow for larger files.
> 
> GeoPandas also supports a different IO engine, [Pyogrio](https://pyogrio.readthedocs.io), that is optimised for reading and writing data in bulk rather than row-per-row. Just make sure the `pyogrio` package is installed, and add the `engine="pyogrio"` parameter to your [gpd.read_file](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html) call. This should give a significant performance improvement (~5x up to 20x faster).
> 
> If you want some more improvement, you can install the `pyarrow` package as well, and add the `use_arrow=True` parameter to `read_file` in addition to `engine="pyogrio"`. In most situations this gives another significant performance boost.
> 
> For the next major version of GeoPandas, planned to be released ~next month, it is planned to switch the default IO engine from Fiona to Pyogrio.

Thanks a lot! It became much faster after engine="pyogrio" was added.
However, I wonder that, now that engine="pyogrio" can accelerate reading files so significantly, why engine="pyogrio" is not the default option? Is there any disadvantages of using engine = "pyogrio"?

**Comment by theroggy** [comment] 2024-03-07 06:35
As mentioned, the default will switch in the next major version:

> For the next major version of GeoPandas, planned to be released ~next month, it is planned to switch the default IO engine from Fiona to Pyogrio.

The reason it is only in the next version is because the switch is not fully backwards compatible: some less used features of Fiona are not supported by Pyogrio, and Pyogrio also has some extra features compared to Fiona. So, for some existing code bases some work will be involved, so the switch is only being done in the new major of GeoPandas.

**Closed** 2024-03-07 06:37 UTC
Labels: bug, needs triage
