### ISSUE TITLE
Unwanted transformation from GeoDataFrame to DataFrame

### ISSUE THREAD

**Issue by philippschw** [geopandas/geopandas#314] opened 2016-05-08 16:35 UTC
In [23]:`type(gp_df_shapefile)`
Out [23]: geopandas.geodataframe.GeoDataFrame

In [24]: `gp_df_shapefile= gp_df_shapefile[gp_df_shapefile['column'].notnull()]`

In [25]: `type(Joined_Shapefile_Rasterdata)`
Out [26]: pandas.core.frame.DataFrame

Example documents unwanted transformation from GeoDataFrame to DataFrame when notnull() is used to retrieve subset of GeoDataFrame.

Edit:
Same problem with: `gp_df_shapefile= gp_df_shapefile[np.isfinite(gp_df_shapefile['column'])]`

**Comment by philippschw** [comment] 2016-05-08 16:41
Solution to drop rows with nan in specific column:

`gp_df_shapefile= gp_df_shapefile.dropna(subset=['column']) `

**Comment by oztalha** [comment] 2017-03-04 20:25
dropna does nothing on geoseries:
```
a = gpd.GeoSeries([1, 2, pd.np.nan, 3])
a.dropna()
```
Actual:
```
0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64
```
Expected:
```
0    1.0
1    2.0
3    3.0
dtype: float64
```

**Comment by jorisvandenbossche** [comment] 2017-03-04 20:53
@oztalha Note that it is not the purpose of a GeoSeries to hold numeric values. 
But apart from that, you seem to have encountered a bug, as also with geometrical values this is an issue:

```
In [54]: from shapely.geometry import Point

In [56]: a = gpd.GeoSeries([Point(1,1), Point(2,2), pd.np.nan, Point(3,3)])

In [58]: a.dropna()
Out[58]: 
0    POINT (1 1)
1    POINT (2 2)
2            NaN
3    POINT (3 3)
dtype: object

In [59]: a.isnull()
Out[59]: 
0    False
1    False
2     True
3    False
dtype: bool
```

The reason for this is that the attribute `_can_hold_na` is set to False,

```
In [60]: a._can_hold_na
Out[60]: False
```

which should be True I think (not sure why this is set to False, it's done in the geopandas code). 
@oztalha Interested to do a PR to fix this?

**Comment by martinfleis** [comment] 2020-04-19 10:06
I cannot reproduce initial issue (it correctly returns GeoDataFrame) and second mention issue with NaN values has been fixed. Closing and both are likely fixed now.

**Closed by martinfleis** 2020-04-19 10:06 UTC
