### ISSUE TITLE
Index type is lost when filtering to empty geo data frame

### ISSUE THREAD

**Issue by simon-keith** [geopandas/geopandas#1190] opened 2019-11-05 17:03 UTC
## Description
When filtering a GeoDataFrame with a condition that returns no `True` value, so that the resulting dataset is empty, the type of the index is lost.

## Test
```python
import pandas as pd
import geopandas as gpd
from datetime import timedelta, datetime
from shapely.geometry import Point


df = pd.DataFrame(dict(geometry=[Point(i, i) for i in range(3)], timestamp=[datetime.now() + timedelta(seconds=i) for i in range(3)])).set_index("timestamp")
gdf = gpd.GeoDataFrame(df)
max_date = df.index.max()

df_filtered = df.loc[df.index > max_date, :]
gdf_filtered = gdf.loc[gdf.index > max_date, :]
print(df_filtered.index)
print(gdf_filtered.index)
```

### Output
```python
DatetimeIndex([], dtype='datetime64[ns]', name='timestamp', freq=None) 
DatetimeIndex([], dtype='datetime64[ns]', name='timestamp', freq=None)
```
### Environment
```
attrs==19.3.0
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
Fiona==1.8.9.post2
geopandas==0.5.1
munch==2.5.0
numpy==1.17.3
pandas==0.25.3
pyproj==2.4.0
python-dateutil==2.8.1
pytz==2019.3
Shapely==1.6.4.post2
six==1.12.0
```

### Output
```python
DatetimeIndex([], dtype='datetime64[ns]', name='timestamp', freq=None) 
RangeIndex(start=0, stop=0, step=1)
```

### Environment
```
attrs==19.3.0
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
Fiona==1.8.9.post2
geopandas==0.6.1
munch==2.5.0
numpy==1.17.3
pandas==0.25.3
pyproj==2.4.0
python-dateutil==2.8.1
pytz==2019.3
Shapely==1.6.4.post2
six==1.12.0
```

**Comment by jorisvandenbossche** [comment] 2019-11-05 17:47
@simon-keith thanks a lot for the clear, reproducible bug report!

I can reproduce this on 0.6.1, but not with master. So something might have fixed this already. In which case, we should add a test and could backport it to 0.6.x

**Comment by simon-keith** [comment] 2019-11-05 18:30
Thanks for quick reply. If I remember correctly, it used to be an issue in Pandas too until not so long ago.

**Comment by jorisvandenbossche** [comment] 2019-11-11 13:43
I could find a small reproducer that shows a difference in the `take` method (further investigating further now if this is the cause / why that works on pandas master and not on released pandas):

With geopandas 0.5.1
```
In [2]: from shapely.geometry import Point 

In [3]: df = GeoDataFrame({'a': [1, 2, 3], 'geometry': [Point(1,1), Point(2,2), Point(3,3)]}, index=pd.date_range("2012-01-01", periods=3)) 
   ...: inds = np.array([], dtype='int64')     

In [4]: df.take(inds, axis=0)   
Out[4]: 
Empty GeoDataFrame
Columns: [a, geometry]
Index: []

In [5]: df.take(inds, axis=0).index 
Out[5]: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [6]: pd.__version__    
Out[6]: '0.25.3'

In [7]: geopandas.__version__  
Out[7]: '0.5.1'
``` 

and with geopandas 0.6.1:

```
In [4]: df.take(inds, axis=0)  
Out[4]: 
Empty GeoDataFrame
Columns: [a, geometry]
Index: []

In [5]: df.take(inds, axis=0).index  
Out[5]: RangeIndex(start=0, stop=0, step=1)

In [6]: pd.__version__ 
Out[6]: '0.25.3'

In [7]: geopandas.__version__  
Out[7]: '0.6.1'
```

**Comment by jorisvandenbossche** [comment] 2019-11-11 14:23
OK, I found the change that explains why it fails with released pandas but works with pandas master.

Pandas 0.25:

```
In [18]: df = pd.DataFrame({'a':[1, 2, 3], 'b': [.2, .3, .4]}, index=pd.date_range("2012-01-01", periods=3))

In [20]: df_empty = df[:0] 

In [21]: df_empty.index 
Out[21]: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [22]: df_empty['a'] = np.array([], dtype='int64')  

In [23]: df_empty.index   
Out[23]: RangeIndex(start=0, stop=0, step=1)

In [24]: pd.__version__ 
Out[24]: '0.25.3'
```

With pandas master:

```
In [1]: df = pd.DataFrame({'a':[1, 2, 3], 'b': [.2, .3, .4]}, index=pd.date_range("2012-01-01", periods=3))

In [2]: df_empty = df[:0] 

In [3]: df_empty.index  
Out[3]: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [4]: df_empty['a'] = np.array([], dtype='int64')   

In [5]: df_empty.index
Out[5]: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [6]: pd.__version__ 
Out[6]: '0.26.0.dev0+822.g6b06f4342.dirty'
```

So assigning to a column of an empty frame resets the index on released pandas, but this has been fixed to preserve the index on pandas master.

And with GeoPandas 0.6, we started to rely on this pattern to write the geometries into the array (and thus also do this for empty geodataframes), hence introducing this regression for released pandas versions.

**Closed** 2019-11-15 09:52 UTC
Labels: bug
