### ISSUE TITLE
set Point  use .loc[idx, 'geometry']  on a gdf with 2 row

### ISSUE THREAD

**Issue by xuqinghan** [geopandas/geopandas#886] opened 2018-12-25 06:17 UTC
demo.py :
```
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point,LineString, Polygon

geom_point = Point(1,1)
geom_line = LineString([(0,0),(1,1)])
geom_polygon = Polygon([(0,0),(0,1),(1,1),(1,0)])
print(np.array(geom_point))
print(np.array(geom_line))
print(np.array(geom_polygon))

#1 row set point item by .loc[idx,'geometry'] OK
records = [{'id':1,'attr':2,'geometry':Point(0,1)}]
gdf1 = gpd.GeoDataFrame(data=pd.DataFrame.from_records(records,index='id'),geometry='geometry')
print(gdf1)
gdf1.loc[1,'geometry'] = Point(1,1)

#3 row setitem by .loc[] OK
records = [{'id':1,'attr':2,'geometry':Point(0,1)},
           {'id':2,'attr':2,'geometry':Point(0,2)},
           {'id':3,'attr':2,'geometry':Point(0,3)}]
gdf1 = gpd.GeoDataFrame(data=pd.DataFrame.from_records(records,index='id'),geometry='geometry')
print(gdf1)
gdf1.loc[1,'geometry'] = Point(1,1)


#2 row  Can't set point by .loc[idx,'geometry']  !
records = [{'id':1,'attr':2,'geometry':Point(0,1)},
           {'id':2,'attr':2,'geometry':Point(0,2)}]
gdf1 = gpd.GeoDataFrame(data=pd.DataFrame.from_records(records,index='id'),geometry='geometry')
print(gdf1)
gdf1.loc[1,'geometry'] = geom_polygon
gdf1.loc[1,'geometry'] = geom_line
gdf1.loc[1,'geometry'] = geom_point

#Can't set point by .loc[idx,'geometry'] with new id !
records = [{'id':1,'attr':2,'geometry':Point(0,1)}]
gdf1 = gpd.GeoDataFrame(data=pd.DataFrame.from_records(records,index='id'),geometry='geometry')
print(gdf1)
gdf1.loc[2,'geometry'] = geom_polygon
gdf1.loc[2,'geometry'] = geom_line
gdf1.loc[2,'geometry'] = geom_point
```
Error is

>   File "C:\Users\xcsc\.virtualenvs\lazyman35-quotation-MWo-woSM\lib\site-packages\pandas\core\internals.py", line 936, in setitem
>     values = values.astype(arr_value.dtype)
> TypeError: float() argument must be a string or a number, not 'Point'

only Point failed when gdf.shape[0] == 2, and cant work with new idx.  but LineString and Polygon never failed.

in pandas' internal.py:

```
        if _is_empty_indexer(indexer):
            pass

        # setting a single element for each dim and with a rhs that could
        # be say a list
        # GH 6043
        elif _is_scalar_indexer(indexer):
            values[indexer] = value
        # if we are an exact match (ex-broadcasting),
        # then use the resultant dtype
        elif (len(arr_value.shape) and
              **arr_value.shape**[0] == values.shape[0] and
              np.prod(arr_value.shape) == np.prod(values.shape)):
            values[indexer] = value
            try:
                **values = values.astype(arr_value.dtype)**
            except ValueError:
                pass

        # set
        else:
            values[indexer] = value

```
where:
`arr_value = np.array(value)`

only Point  return a 2*1 list [x,y]  so it  will fail when gdf with 2 rows.

could add a patch on GeoDataFrame (override the setitem()? ) for this subtle case ?   ^_^!!

**Comment by jGaboardi** [comment] 2018-12-25 13:36
This is a duplicate of #831

**Comment by martinfleis** [comment] 2019-10-09 19:34
This seems to be fixed, I am not able to replicate the issue, the example above works. @xuqinghan can you check if the issue still exists in Geopandas 0.6?

**Comment by jdmcbr** [comment] 2020-10-17 05:27
Likewise, can't reproduce this now. @xuqinghan if you're still seeing this, happy to re-open, but will close this for now.

**Closed by jdmcbr** 2020-10-17 05:27 UTC
