### ISSUE TITLE
BUG:  Overlay with how intersects and difference

### ISSUE THREAD

**Issue by sehHeiden** [geopandas/geopandas#2230] opened 2021-11-18 11:21 UTC
####  Summarry
I discovered a problem with the **overlay** function in geopandas espacially for *how=difference*  and others (in most of these cases *how=intersection* still works:).

#### Problem description

```python
Vector3  = overlay(Vector2 , Vector1, how='intersection', keep_geom_type=True)
Vector1_new =overlay(Vector1, Vector3, how='difference', keep_geom_type=True)
```
I  often get the Error: shapely.errors.TopologicalError

and very seldom get the same error when:
```python
Vector3  = overlay(Vector2 , Vector1, how='intersection', keep_geom_type=True)
vector4 = overlay(Vector1, Vector3, how='intersection', keep_geom_type=True)
```
I checked the polygons. all are valid. I tried to make them valid both with buffering and shapely.validation.make_valid. I tried shapely and pygeos. The error does not (change, but the errormessage for pygeos is different).

But when I create the difference with QGIS everything worked (execpt for one case, when it worked in geopandas instead).

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\remote\anaconda3\envs\ENDUP_SOL\python.exe
machine    : Windows-10-10.0.19041-SP0
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.3
GDAL data dir: None
PROJ       : 8.1.1
PROJ data dir: C:\Users\remote\anaconda3\envs\ENDUP_SOL\Library\share\proj
PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.2.3
fiona      : 1.8.20
numpy      : 1.20.1
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.2.1
matplotlib : 3.4.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: 0.9.2
pyarrow    : None
pygeos     : 0.11.1

</details>

**Comment by martinfleis** [comment] 2021-11-18 12:28
Hi, thanks for the report but I am afraid I didn't really get it. Could you read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug? The reproducible example would help a lot as well as the actual tracebacks.

**Comment by jorisvandenbossche** [comment] 2023-11-11 13:47
Given that we cannot reproduce the issue without more information, going to close this (but @sehHeiden if you still have this issue and could provide more information, that's still very welcome!)

**Closed by jorisvandenbossche** 2023-11-11 13:46 UTC
Labels: bug, needs info
