### ISSUE TITLE
read_file on an empty layer in a gdb results in an IndexError

### ISSUE THREAD

**Issue by kylebarron** [geopandas/geopandas#1184] opened 2019-10-28 21:26 UTC
Possibly related to #435 and/or #757. 

I'm unable to open a layer of a GeoDatabase file that has no rows. To reproduce:
```bash
wget https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/WBD/HU2/GDB/WBD_17_HU2_GDB.zip
```

```py
import geopandas as gpd
gpd.read_file('WBD_17_HU2_GDB.zip', layer='ExternalCrosswalk')
```

That raises the below traceback. It looks something like the data is an array of [0x0] and the header is an array of [7x1] and they can't combine?

I'm on MacOS. Fiona version '1.8.7'. GeoPandas version '0.6.0'. GDAL 2.4.2.

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~barron/anaconda/envs/create-database/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/core/frame.py in _repr_html_(self)
    685                 show_dimensions=show_dimensions,
    686             )
--> 687             formatter.to_html(notebook=True)
    688             return formatter.buf.getvalue()
    689         else:

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/format.py in to_html(self, classes, notebook, border)
    838 
    839         Klass = NotebookFormatter if notebook else HTMLFormatter
--> 840         html = Klass(self, classes=classes, border=border).render()
    841         if hasattr(self.buf, "write"):
    842             buffer_put_lines(self.buf, html)

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in render(self)
    604         self.write("<div>")
    605         self.write_style()
--> 606         super().render()
    607         self.write("</div>")
    608         return self.elements

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in render(self)
    191 
    192     def render(self) -> List[str]:
--> 193         self._write_table()
    194 
    195         if self.should_show_dimensions:

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in _write_table(self, indent)
    233             self._write_header(indent + self.indent_delta)
    234 
--> 235         self._write_body(indent + self.indent_delta)
    236 
    237         self.write("</table>", indent)

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in _write_body(self, indent)
    379     def _write_body(self, indent: int) -> None:
    380         self.write("<tbody>", indent)
--> 381         fmt_values = self._get_formatted_values()
    382 
    383         # write values

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in _get_formatted_values(self)
    568 
    569     def _get_formatted_values(self) -> Dict[int, List[str]]:
--> 570         return {i: self.fmt._format_col(i) for i in range(self.ncols)}
    571 
    572     def _get_columns_formatted_values(self) -> List[str]:

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/html.py in <dictcomp>(.0)
    568 
    569     def _get_formatted_values(self) -> Dict[int, List[str]]:
--> 570         return {i: self.fmt._format_col(i) for i in range(self.ncols)}
    571 
    572     def _get_columns_formatted_values(self) -> List[str]:

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/format.py in _format_col(self, i)
    815             na_rep=self.na_rep,
    816             space=self.col_space,
--> 817             decimal=self.decimal,
    818         )
    819 

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal, leading_space)
   1031     )
   1032 
-> 1033     return fmt_obj.get_result()
   1034 
   1035 

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/format.py in get_result(self)
   1062 
   1063     def get_result(self):
-> 1064         fmt_values = self._format_strings()
   1065         return _make_fixed_width(fmt_values, self.justify)
   1066 

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/pandas/io/formats/format.py in _format_strings(self)
   1328             values = values._values
   1329 
-> 1330         formatter = values._formatter(boxed=True)
   1331 
   1332         if is_categorical_dtype(values.dtype):

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/geopandas/array.py in _formatter(self, boxed)
   1001                 # dummy heuristic based on 10 first geometries that should
   1002                 # work in most cases
-> 1003                 xmin, ymin, xmax, ymax = self[~self.isna()][:10].total_bounds
   1004                 if (
   1005                     (-180 <= xmin <= 180)

~barron/anaconda/envs/create-database/lib/python3.7/site-packages/geopandas/array.py in total_bounds(self)
    750         return np.array(
    751             (
--> 752                 b[:, 0].min(),  # minx
    753                 b[:, 1].min(),  # miny
    754                 b[:, 2].max(),  # maxx

IndexError: too many indices for array
Empty GeoDataFrame
Columns: [TNMID, ExternalID, ExternalIDName, ExternalIDOriginator, OrganizationType, ExternalIDEntryDate, geometry]
Index: []
```

**Comment by jorisvandenbossche** [comment] 2019-10-29 08:10
@kylebarron thanks for the report!

I actually think that the reading itself is fine, but only printing the representation of it seems to fail. But it seems to be fixed on 0.6.1 for me (could you upgrade to that to verify?).

**Comment by jorisvandenbossche** [comment] 2019-10-29 08:13
Actually, it is in the notebook that the repr is still failing:

```
In [34]: df = geopandas.read_file('WBD_17_HU2_GDB.zip', layer='ExternalCrosswalk')

In [35]: df 
Out[35]: 
Empty GeoDataFrame
Columns: [TNMID, ExternalID, ExternalIDName, ExternalIDOriginator, OrganizationType, ExternalIDEntryDate, geometry]
Index: []

In [36]: df._repr_html_()
...
IndexError: too many indices for array
```

That is clearly a regression we should fix!

**Comment by kylebarron** [comment] 2019-10-29 11:58
Ah yes, I'm working through Jupyter (specifically in [Hydrogen](http://github.com/nteract/hydrogen)), so it would be calling the `__repr_html__`.

**Closed** 2019-11-13 08:20 UTC
