### ISSUE TITLE
BUG: `to_postgis()` fails with Geoalchemy 11

### ISSUE THREAD

**Issue by iboates** [geopandas/geopandas#2386] opened 2022-03-21 16:43 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

A recent release of [geoalchemy 0.11.1](https://github.com/geoalchemy/geoalchemy2/releases/tag/0.11.1) has broken `.to_postgis()`

```python
from sqlalchemy import create_engine
engine = create_engine("postgresql://myusername:mypassword@myhost:5432/mydatabase")  
path = gpd.datasets.get_path('naturalearth_lowres')
gdf = gpd.read_file(path)
gdf.to_postgis("my_table", engine)  
```

returns an exception complaining about a pre-existing index (see below). I don't know if this is a problem on geoalchemy2's end or on geopandas', but when I rolled back geoalchemy2 to version 0.10.2, it worked again.

```
Traceback (most recent call last):
  File "/home/boates/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1683, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/geopandas/io/sql.py", line 431, in _write_postgis
    gdf.to_sql(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 2872, in to_sql
    sql.to_sql(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1751, in to_sql
    table = self.prep_table(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 867, in create
    self._execute_create()
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 853, in _execute_create
    self.table.create()
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 950, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 905, in visit_table
    self.traverse_single(index, create_ok=True)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 936, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/boates/_code/microgrid-support/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "idx_my_table_geometry" already exists
[SQL: CREATE INDEX idx_my_table_geometry ON public.my_table USING gist (geometry)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by martinfleis** [comment] 2022-03-22 20:36
duplicate of #2375

**Closed by martinfleis** 2022-03-22 20:36 UTC
Labels: bug, needs triage
