### ISSUE TITLE
BUG: CRS not set for some of the concatenation inputs warning after setting geometry.

### ISSUE THREAD

**Issue by ennoToUpper** [geopandas/geopandas#2931] opened 2023-06-15 09:49 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas
import pandas
import shapely

point = shapely.Point(600000, 5000000)

df_1 = geopandas.GeoDataFrame(data={"geom": [shapely.Point([1, 2])]}, geometry="geom", crs="25832")

df_merged = df_1.merge(df_1, left_index=True, right_index=True)

# df_merged.set_geometry("geom_y", inplace=True, crs="25832") 
# Causes: ValueError: Can't do inplace setting when converting from DataFrame to GeoDataFrame
# Maybe a clue for devs, yet in my project the warning shows up even when it's a GeoDataFrame.
df_merged = df_merged.set_geometry("geom_y", crs="25832")

temp_df = pandas.concat([df_merged, df_1], ignore_index=True)
# Causes: ..\geopandas\array.py:1406: UserWarning: CRS not set for some of the concatenation inputs. Setting output's CRS as ETRS89 / UTM zone 32N (the single non-null crs provided).
#  warnings.warn(
```

#### Problem description

Only when concatenating after setting a different geometry than the first set one will cause the issue. This can happen in many cases like merging dataframes and using the other geometry or the "set_geometry- using an existing column" example ([Geopandas Documentation](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.set_geometry.html)) and setting the geometry afterwards.

Having to concatenate many dataframes into one this issue will flood the console with warnings.
Also the warning seems incomplete and is hit multiple times per concat (though only one warning is displayed).

#### Expected Output

No warning as setting the geometry is a valid step and it is working without an issue other than the warning.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
executable : C:\Users\max\AppData\Local\Programs\Python\Python311\python.exe
machine    : Windows-10-10.0.19045-SP0
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.5.2
GDAL data dir: C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\fiona\gdal_data
PROJ       : 9.2.0
PROJ data dir: C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyproj\proj_dir\share\proj
PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.24.2
pandas     : 2.0.0
pyproj     : 3.5.0
shapely    : 2.0.1
fiona      : 1.9.3
geoalchemy2: 0.13.2
geopy      : None
matplotlib : None
mapclassify: None

</details>

**Comment by m-richards** [comment] 2023-06-16 10:27
@ennoToUpper would you be able to try this again on the latest version of GeoPandas? I am unable to reproduce this on main. I believe this is a duplicate of #2679 which was fixed in 0.13 (#2680, which it seems I forgot to add a changelog entry for).

> ```
> # df_merged.set_geometry("geom_y", inplace=True, crs="25832") 
> # Causes: ValueError: Can't do inplace setting when converting from DataFrame to GeoDataFrame
> # Maybe a clue for devs, yet in my project the warning shows up even when it's a GeoDataFrame.
> ```

I am not sure what you mean by this - this is expected - it doesn't really make sense to try and do something inplace if the type of the class is changed by the operation.

**Comment by ennoToUpper** [comment] 2023-06-16 13:53
> @ennoToUpper would you be able to try this again on the latest version of GeoPandas? I am unable to reproduce this on main. I believe this is a duplicate of https://github.com/geopandas/geopandas/issues/2679 which was fixed in 0.13 (https://github.com/geopandas/geopandas/pull/2680, which it seems I forgot to add a changelog entry for).

I guess I have an issue with my virtual environment. pip reported it as being the latest version, in the package manager it showed 12.2. . So everytime I checked for an update it did download it but used the old one. Sorry for that I did not realize that there was an isse.
There is no warning in 13.3 for me.

> I am not sure what you mean by this - this is expected - it doesn't really make sense to try and do something inplace if the type of the class is changed by the operation.

The behaviour makes sense yet I wondered why I got a Dataframe in the first place. I included the comment as I figured it might hint to a cause somewhere.
That being said I don't understand how I don't get a GeoDataframe in return as I call the method on a GeoDF and I also supply it with one. According to the description it should return a Dataframe only when there is no geometry column which there is in this case.

On a side note it would be helpful to see which parameters are needed or can be used instead of args and kwargs. For me geopandas is the first contact with pandas so I am not familiar with the merge method.

**Comment by m-richards** [comment] 2023-06-18 07:32
```
df_merged = df_1.merge(df_1, left_index=True, right_index=True)
In [2]: type(df_merged)
Out[2]: pandas.core.frame.DataFrame
```
This returns a Dataframe because there is no active geometry column associated with it - when you do the self merge, the column `geom` is lost and replaced with `geom_x` and `geom_y`. Now this is a bit of an unfortunate case, I would expect our behaviour to return a GeoDataFrame without an active geometry column here (you're correct that getting a DataFrame back here is incorrect), in the same way as
```python
In [12]: pd.concat([df_1.geom.rename("geom_x"), df_1.geom.rename("geom_y")], axis=1)
Out[12]:
                geom_x               geom_y
0  POINT (1.000 2.000)  POINT (1.000 2.000)

In [13]: type(pd.concat([df_1.geom.rename("geom_x"), df_1.geom.rename("geom_y")], axis=1))
Out[13]: geopandas.geodataframe.GeoDataFrame
```
This has less confusing behaviour in that it will show a more helpful error message:
```
In [14]: res =pd.concat([df_1.geom.rename("geom_x"), df_1.geom.rename("geom_y")], axis=1)
In [16]: res.geometry
AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column to use has not been set.
There are columns with geometry data type (['geom_x', 'geom_y']), and you can either set one as the active geometry with df.set_geometry("name") or access the column as a GeoSeries (df["name"]) and call the method directly on it.
```

I will move this discussion to a new issue focusing specficially on this problem (and perhaps we can fix the args, kwargs at the same time)

**Closed by m-richards** 2023-06-18 07:32 UTC
Labels: bug, needs triage

**Comment by ennoToUpper** [comment] 2023-06-19 07:38
> This returns a Dataframe because there is no active geometry column associated with it - when you do the self merge, the column geom is lost and replaced with geom_x and geom_y. Now this is a bit of an unfortunate case, I would expect our behaviour to return a GeoDataFrame without an active geometry column here.

Now it makes sense why it works in my project but not in the code snippet. In the project I specifically use an empty string as suffix for one side. Thank you!
