### ISSUE TITLE
Error while importing Geopandas

### ISSUE THREAD

**Issue by FurquanAnwer** [geopandas/geopandas#2123] opened 2021-09-23 07:42 UTC
I have installed geopandas using !pip install geopandas.
Before installing geopandas I installed gdal and fiona using the same method.
But while importing geopandas, following error appears always.
How do I rectify it ?

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fc7d1d298f0c> in <module>
----> 1 import geopandas

~\anaconda3\lib\site-packages\geopandas\__init__.py in <module>
      5 from geopandas.array import points_from_xy  # noqa
      6 
----> 7 from geopandas.io.file import _read_file as read_file  # noqa
      8 from geopandas.io.arrow import _read_parquet as read_parquet  # noqa
      9 from geopandas.io.arrow import _read_feather as read_feather  # noqa

~\anaconda3\lib\site-packages\geopandas\io\file.py in <module>
     18 
     19 try:
---> 20     from fiona import Env as fiona_env
     21 except ImportError:
     22     try:

~\anaconda3\lib\site-packages\fiona\__init__.py in <module>
     86 
     87 import fiona._loading
---> 88 with fiona._loading.add_gdal_dll_directories():
     89     from fiona.collection import BytesCollection, Collection
     90     from fiona.drvsupport import supported_drivers

AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)
```

**Comment by martinfleis** [comment] 2021-09-23 08:21
Check this discussion over in fiona repository https://github.com/Toblerity/Fiona/issues/944. 

Installing via pip can be challenging and we generally recommend using conda if that is possible. One thing you may try is to import fiona before importing geopandas. That fixes the circular import issue in some cases (but obviously doesn't resolve it).

```py
import fiona
import geopandas
```

**Comment by anitagraser** [comment] 2021-09-25 18:07
Hi @martinfleis, a similar error (without the not that it may be due to circular import) appeared on Travis https://app.travis-ci.com/github/anitagraser/movingpandas/builds/238483202

![image](https://user-images.githubusercontent.com/590385/134781643-85068b12-99c0-4a1f-bb9a-c40253c22577.png)

Should I open a separate issue?

**Comment by jorisvandenbossche** [comment] 2021-09-25 18:41
There is already quite some discussion about this in the fiona issue that Martin linked (and see also https://github.com/geopandas/geopandas/issues/1992, https://github.com/geopandas/geopandas/pull/2112 in geopandas).

But it's interesting that you have this in CI, which might make it possible to reproduce this (and see if some changes in geopandas can fix this).

**Comment by jorisvandenbossche** [comment] 2021-09-25 20:21
OK, I can reproduce this by using the environment.yml file from movingpandas, and recreating that environment locally. 

But, it seems this is actually an issue with the fiona install, because importing it on itself gives the following error (at least this is the issue for me locally, not 100% sure it's the same issue on CI):

```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/envs/movingpandas/lib/python3.7/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/joris/miniconda3/envs/movingpandas/lib/python3.7/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libdeflate.so.0: cannot open shared object file: No such file or directory
>>> import geopandas
```

But, so we are masking this import error message at the moment, and letting geopandas' import fail because of fiona's import error (which we don't want to do, since it's an optional dependency now). 

It seems that https://github.com/geopandas/geopandas/pull/2112 might fix this specific issue (in case that fiona's install is actually broken)

**Comment by jorisvandenbossche** [comment] 2021-09-26 08:26
@anitagraser I have a fix at https://github.com/geopandas/geopandas/pull/2139 for this issue, will be in the upcoming 0.9 release (planned for coming week)

But so for Travis CI, your actual issue to solve is that the fiona install is broken. That might be an upstream conda-forge issue. Because creating a new, clean env all from conda-forge should normally work.

The issue in https://github.com/anitagraser/EDA-protocol-movement-data/issues/2 still seems something different (I don't think that one stems from a broken fiona install)

**Comment by jorisvandenbossche** [comment] 2021-09-26 11:04
@anitagraser I reported the broken install you see in Travis CI (and which I could reproduce locally) at https://github.com/conda-forge/gdal-feedstock/issues/537. It seems to be a bad interaction between fiona/gdal and geoviews.

**Comment by anitagraser** [comment] 2021-09-26 12:08
Thank you @jorisvandenbossche !

**Comment by anitagraser** [comment] 2021-10-03 18:05
Glad to report that Travis is happy again: https://app.travis-ci.com/github/anitagraser/movingpandas/builds/238483202

**Closed** 2023-01-05 22:08 UTC
Labels: installation
