### ISSUE TITLE
encoding error reading back dataframe i just saved

### ISSUE THREAD

**Issue by simonm3** [geopandas/geopandas#1240] opened 2019-12-23 14:25 UTC
When I try to read back a file saved using geopandas I get an encoding error. It works if I specify encoding=utf8 on save. However it would make more sense to fail on save. Otherwise you save some data and lose access because you cannot read it back.
```
gdf.to_file("popshapes.geojson", driver="GeoJSON")
gpd.read_file("popshapes.geojson")
```

**Comment by martinfleis** [comment] 2019-12-23 15:36
Hi @simonm3, thanks for the report. Can you provide a chunk of the original geojson which allows us to reproduce the issue?

**Comment by simonm3** [comment] 2019-12-23 21:14
```
df = gpd.read_file("popshapes.geojson")
gdf.to_file("popshapes2.geojson", driver="GeoJSON")
df = gpd.read_file("popshapes2.geojson")
```
[popshapes.zip](https://github.com/geopandas/geopandas/files/3996307/popshapes.zip)

**Comment by jorisvandenbossche** [comment] 2019-12-23 21:27
I cannot reproduce this with the uploaded data:

```
In [5]: df = geopandas.read_file("popshapes.geojson")

In [6]: df.to_file("popshapes2.geojson", driver="GeoJSON") 

In [7]: df2 = geopandas.read_file("popshapes2.geojson") 

In [8]: df2  
Out[8]: 
                          label_out                                           geometry
0                      0-Koya=4,941  POLYGON ((5.56250 13.85667, 5.55250 13.85833, ...
1                      1-Dawa=4,222  POLYGON ((5.58500 13.84333, 5.58083 13.84500, ...
2      2-Kamagata Health Post=3,769  POLYGON ((5.70250 13.79667, 5.69667 13.79833, ...
3                     3-Marma=9,434  POLYGON ((5.35667 13.78333, 5.34583 13.78833, ...
4     4-Jirgabawa Health Post=4,638  POLYGON ((5.40917 13.76750, 5.40417 13.77417, ...
...                             ...                                                ...
2114              2114-Wambai=7,282  POLYGON ((7.46167 4.97583, 7.45167 4.98583, 7....
2115              2115-Ganuwa=4,635  POLYGON ((8.06417 4.95583, 8.05250 4.97583, 8....
2116               2116-Dokau=4,710  POLYGON ((8.13750 4.86917, 8.13583 4.87083, 8....
2117              2117-Iressa=4,816  POLYGON ((7.61417 4.80167, 7.61250 4.80250, 7....
2118               2118-Ikang=9,464  POLYGON ((8.52917 4.78667, 8.51583 4.79750, 8....

[2119 rows x 2 columns]
```

Can you give some more details about your system? (eg show the output `geopandas.show_versions()`) Can you also show the full error traceback?

**Comment by simonm3** [comment] 2019-12-24 10:19
SYSTEM INFO
-----------
python     : 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
executable : C:\Users\simon\Anaconda3\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Users\simon\Anaconda3\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.6.1
pandas     : 0.24.2
fiona      : 1.8.11
numpy      : 1.16.2
shapely    : 1.6.4.post2
rtree      : 0.8.3
pyproj     : 2.4.1
matplotlib : 3.1.2
mapclassify: None
pysal      : None
geopy      : 1.20.0
psycopg2   : None


fiona.ogrext:WARNING]:Failed to decode b'248-Jama\x92ar Kasa=7,553'
using utf-8 codec (geodataframe.py:283, time=Dec-24 10:17)

TypeError                                 Traceback (most recent call
last)<ipython-input-17-5b4466df4c02> in <module>      1 df =
gpd.read_file("popshapes.geojson")      2
df.to_file("popshapes2.geojson", driver="GeoJSON")----> 3 df2 =
gpd.read_file("popshapes2.geojson")
~\Anaconda3\lib\site-packages\geopandas\io\file.py in
read_file(filename, bbox, **kwargs)     93      94             columns
= list(features.meta["schema"]["properties"]) + ["geometry"]---> 95
         gdf = GeoDataFrame.from_features(f_filt, crs=crs,
columns=columns)     96      97     return gdf
~\Anaconda3\lib\site-packages\geopandas\geodataframe.py in
from_features(cls, features, crs, columns)    281     282         rows
= []--> 283         for f in features_lst:    284             if
hasattr(f, "__geo_interface__"):    285                 f =
f.__geo_interface__
fiona/ogrext.pyx in fiona.ogrext.Iterator.__next__()
fiona/ogrext.pyx in fiona.ogrext.FeatureBuilder.build()
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by martinfleis** [comment] 2020-01-04 12:17
The issue is very similar to as #1231. Windows saves geojson in `windows-1252` encoding even though it should be `utf-8`. I can reproduce it on mac via 

`df.to_file("popshapes2.geojson", driver="GeoJSON", encoding='windows-1252')`

Then it raises the error above. In this case, you should specify encoding during `to_file` to be `utf-8`. Then it should work correctly.

However, I am not sure why Fiona uses `windows-1252` because in [JSON specification](https://tools.ietf.org/html/rfc7159#section-8.1) is UTF only. We can in theory use UTF for geojson by default, but I feel that this should be handled on Fiona side. (cc @sgillies)

**Comment by sgillies** [comment] 2020-01-06 17:29
The `fiona.ogrext:WARNING]:Failed to decode b'248-Jama\x92ar Kasa=7,553'
using utf-8 codec` log message reported by @simonm3 comes from https://github.com/Toblerity/Fiona/blob/maint-1.8/fiona/ogrext.pyx#L222-L228. This signals to me that iconv support may be lacking in the conda-forge package. @simonm3 do you see a similar warning emitted when *saving* the GeoJSON file?

**Comment by simonm3** [comment] 2020-01-06 18:39
No there is no error message when saving. Just you cannot read it back
without knowing the encoding.

**Comment by sgillies** [comment] 2020-01-06 21:25
@simonm3 @martinfleis I've found the problem and am looking for it to be solved in GDAL/OGR: https://github.com/OSGeo/gdal/issues/2151. The way this affects fiona and GeoPandas is that this line https://github.com/Toblerity/Fiona/blob/maint-1.8/fiona/ogrext.pyx#L566 evaluates to False and so we fall back to the default encoding on your computer, which is presumably latin-1 or windows-1252.

It might be determined that fiona is misusing the OGR API, in which case we'll need to make a special case for GeoJSON in that function.

Meanwhile, the workaround is to make sure that your environment's default encoding is UTF-8 when you run your program.

**Comment by martinfleis** [comment] 2022-02-19 23:34
This was most likely fixed in https://github.com/OSGeo/gdal/pull/2152. We can reopen if not.

**Closed by martinfleis** 2022-02-19 23:34 UTC
Labels: needs info
