### ISSUE TITLE
BUG: Coordinate shift after reprojecting

### ISSUE THREAD

**Issue by cratcliff** [geopandas/geopandas#2405] opened 2022-04-12 03:54 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

```python
import pandas as pd
import geopandas as gpd

df = pd.read_csv('Sample_Dataset.csv')
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df['QGIS_Lon'], df['QGIS_Lat']),crs=4326)

# reproject by epsg
gdf = gdf.to_crs(epsg=28354)
gdf['GPD_East94']= gdf.geometry.apply(lambda p: p.x)
gdf['GPD_North94'] = gdf.geometry.apply(lambda p: p.y)

# Compare differences
gdf['QGIS-GPD_East'] = gdf['QGIS_East']  - gdf['GPD_East94']
gdf['QGIS-GPD_North'] = gdf['QGIS_North']  - gdf['GPD_North94']

```

#### Problem description
I have detected a shift ( ~0.6 easting, ~1.5 northing) when projecting data from WGS 84 (EPSG:4326) to GDA 1994 MGA zone 54 (EPSG:28354). This shift is not seen when the reprojection is completed using QGIS or ArcMap.

Attached is a csv file containing sample data with the expected coordinates as created in QGIS. The QGIS Eastings/Northing values match those derived in ArcMap as well.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``geopandas.show_versions()``
<details> 
abab
</details> 
<details> 

[SYSTEM INFO
-----------
python     : 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:37:49) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\rat062\Miniconda3\envs\pa37_dev\python.exe
machine    : Windows-10-10.0.19041-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.4
GDAL data dir: None
PROJ       : 8.0.1
PROJ data dir: C:\Users\rat062\Miniconda3\envs\pa37_dev\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.7.0
pandas     : 1.3.4
fiona      : 1.8.18
numpy      : 1.21.4
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.2.1
matplotlib : 3.5.0
mapclassify: None
pysal      : None
geopy      : None
psycopg2   : None]

</details>

**Comment by martinfleis** [comment] 2022-04-12 07:40
Duplicate of #2406

**Closed** 2022-04-12 07:40 UTC
Labels: bug, needs triage
