### ISSUE TITLE
Use geo accessor for GeoSeries methods?

### ISSUE THREAD

**Issue by shoyer** [geopandas/geopandas#166] opened 2014-09-19 05:54 UTC
The next version of pandas will introduce a [`.dt` series accessor](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#dt-accessor) for datetime methods, along `.cat` for [categoricals](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#categoricals-in-series-dataframe) and the existing `.str` for string methods.

From this perspective, would it make sense to have geo-specific methods use a `.geo` attribute? e.g., `s.geo.convex_hull` instead of the current `s.convex_hull`.

Just thought I'd throw that out there for consideration, especially if tighter integration with pandas itself is desired at some point (e.g., to plug into the pandas internals at a lower level such that `GeoSeries` and `GeoDataFrame` are not necessary).

**Comment by tswast** [comment] 2023-04-13 17:44
Looks like a duplicate of https://github.com/geopandas/geopandas/issues/680#issuecomment-536486242 (which has a more in-depth discussion)

**Closed** 2024-12-26 18:15 UTC
