### ISSUE TITLE
BUG: clip returns empty line strings

### ISSUE THREAD

**Issue by Oi-sin** [geopandas/geopandas#1841] opened 2021-02-22 16:48 UTC
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas. 
I suppose 0.8.2 is the latest

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import LineString, Polygon

data = {'geometry':  [LineString ([(13.68, 51.06), (13.69, 51.06)]), #<- clipped to empty
                     LineString ([(13.68, 51.06), (13.69, 51.07)]),
                     LineString ([(13.68, 51.06), (13.68, 51.07)])]} #<- clipped to empty
gdf = gpd.GeoDataFrame(data, geometry='geometry', crs='EPSG:4326')

poly = Polygon([[13, 51], [13, 52], [14, 52], [14, 51], [13, 51]])

clipped_gdf = gpd.clip(gdf, poly)
print(clipped_gdf)
```

#### Problem description

Clipping of LineString that have identical values for latitude or longiture returns empty geometries. 

#### Expected Output

LineStrings should be preserved upon clipping if they are inside the given polygone

<details>

SYSTEM INFO
-----------
python     : 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:04:36) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\[USERNAME]\anaconda3\envs\testenv\python.exe
machine    : Windows-10-10.0.19041-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.4
GDAL data dir: None
PROJ       : 7.2.0
PROJ data dir: C:\Users\[USERNAME]\anaconda3\envs\testenv\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.2
pandas     : 1.2.1
fiona      : 1.8.18
numpy      : 1.20.0
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.0.post1
matplotlib : 3.3.4
mapclassify: 2.4.2
geopy      : 2.1.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None

</details>

**Comment by martinfleis** [comment] 2021-02-22 21:00
Hi, can you show the output of `conda list`? I am not able to reproduce this in my environment.

**Comment by Oi-sin** [comment] 2021-02-23 06:16
Thanks for your answer and for trying my code. After restarting my machine I can still reproduce the bug. 

Here is the output of `conda list`. I hope that helps. If you need anything else, please let me know.

<details>

```
# packages in environment at C:\Users\[USERNAME]\anaconda3\envs\testenv:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hba8bd2f_1007    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.4           py38hd8c33c5_1    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
contextily                1.1.0              pyhd8ed1ab_0    conda-forge
cryptography              3.3.1            py38hd8c33c5_1    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.10               h39d44d4_0    conda-forge
fiona                     1.8.18           py38h60f4e94_0    conda-forge
folium                    0.12.0             pyhd8ed1ab_0    conda-forge
fontconfig                2.13.1            h1989441_1004    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.1.4            py38h7b01a69_5    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.8.2              pyhd8ed1ab_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.9.0                h39d44d4_0    conda-forge
geotiff                   1.6.0                h5d775bf_4    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py38haa244fe_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
ipykernel                 5.4.3            py38hc5df569_0    conda-forge
ipython                   7.20.0           py38hc5df569_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.14               ha3510f1_0    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.1.4                hd376e63_5    conda-forge
libglib                   2.66.6               h8c8e623_3    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             he9e54da_1012    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     12.3                 h4f54205_3    conda-forge
librttopo                 1.1.0                ha743252_5    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             5.0.1                h6966176_2    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp-base              1.2.0                h8ffe710_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.2              pyhd8ed1ab_0    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
matplotlib-base           3.3.4            py38h34ddff4_0    conda-forge
mercantile                1.1.6              pyh9f0ad1d_0    conda-forge
mistune                   0.8.4           py38h294d835_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
networkx                  2.5                        py_0    conda-forge
notebook                  6.2.0            py38haa244fe_0    conda-forge
numpy                     1.20.0           py38h0cc643e_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h48faf41_0    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.1            py38h4c96930_0    conda-forge
pandoc                    2.11.4               h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py38hf7ce48b_1    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   0.89.0               h3772339_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h0f1a9bc_3    conda-forge
proj                      7.2.0                h3e70539_1    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.0.post1      py38h0ae89ba_0    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.0                hc9e8b01_5    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyzmq                     20.0.0           py38h7a0e47e_1    conda-forge
rasterio                  1.2.0            py38h5653988_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rtree                     0.9.7            py38h8b54edf_1    conda-forge
scikit-learn              0.24.1           py38ha09990b_0    conda-forge
scipy                     1.6.0            py38h5f893b4_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
shapely                   1.7.1            py38hc55ee08_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
terminado                 0.9.2            py38haa244fe_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.2.3                hf84e3da_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.8                h4e2f164_1    conda-forge
```

</details>

**Comment by GGDRriedel** [comment] 2021-02-23 09:49
I can not reproduce the bug
```
import geopandas as gpd
from shapely.geometry import LineString, Polygon

data = {'geometry':  [LineString ([(13.68, 51.06), (13.69, 51.06)]), #<- clipped to empty
                     LineString ([(13.68, 51.06), (13.69, 51.07)]),
                     LineString ([(13.68, 51.06), (13.68, 51.07)])]} #<- clipped to empty
gdf = gpd.GeoDataFrame(data, geometry='geometry', crs='EPSG:4326')

poly = Polygon([[13, 51], [13, 52], [14, 52], [14, 51], [13, 51]])

clipped_gdf = gpd.clip(gdf, poly)
print(clipped_gdf)
                                            geometry
0  LINESTRING (13.68000 51.06000, 13.69000 51.06000)
1  LINESTRING (13.68000 51.06000, 13.69000 51.07000)
2  LINESTRING (13.68000 51.06000, 13.68000 51.07000)
```


conda list 

```
# packages in environment at C:\Users\Riedel\.conda\envs\spyder-env:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0
anyio                     2.1.0            py38haa244fe_0    conda-forge
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
astroid                   2.4.2                    py38_0
async_generator           1.10                       py_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
audioread                 2.1.9            py38haa244fe_0    conda-forge
autopep8                  1.5.4                      py_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bcrypt                    3.2.0            py38he774522_0
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.2.2              pyhd3eb1b0_0
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.2.3            py38haa244fe_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
bottleneck                1.3.2            py38h347fdf6_3    conda-forge
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cairo                     1.16.0            hba8bd2f_1007    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.4           py38hcd4344a_0
cfitsio                   3.470                h0af3d06_7    conda-forge
cftime                    1.4.1            py38h347fdf6_0    conda-forge
chardet                   4.0.0           py38haa95532_1003
click                     7.1.2              pyhd3eb1b0_0
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.3.1            py38hcd4344a_0
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38hd77b12b_0
cytoolz                   0.11.0           py38h294d835_3    conda-forge
dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2021.2.0         py38haa244fe_0    conda-forge
docutils                  0.16                     py38_1
double-conversion         3.1.5                h6538335_2    conda-forge
eigen                     3.3.9                h2d74725_1    conda-forge
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001    anaconda
expat                     2.2.10               h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
fiona                     1.8.18           py38h60f4e94_0    conda-forge
flake8                    3.8.4                      py_0
fontconfig                2.13.1            h1989441_1004    conda-forge
freetype                  2.10.4               hd328e21_0
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
future                    0.18.2                   py38_1
gdal                      3.1.4            py38h7b01a69_3    conda-forge
geopandas                 0.8.2              pyhd8ed1ab_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h8884d1a_3    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
git                       2.23.0               h6bb4b03_0    anaconda
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
h5py                      3.1.0           nompi_py38h022eade_100    conda-forge
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyhd3eb1b0_0
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.19.0           py38hd4e2768_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.6.4                      py_0
jdcal                     1.4.1                      py_0    anaconda
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.2             pyhd3eb1b0_0
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.8.4             h1ad3211_1002    conda-forge
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.0            py38haa95532_0
jupyter_server            1.3.0            py38haa244fe_0    conda-forge
jupyterlab                3.0.8              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.2.1              pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               h0883a5c_1    conda-forge
keyring                   21.8.0           py38haa95532_0
kiwisolver                1.3.0            py38hd77b12b_0
krb5                      1.17.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.4.3            py38h2bbff1b_2
libclang                  11.0.1          default_h5c34c98_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libflac                   1.3.3                h0e60522_1    conda-forge
libgdal                   3.1.4                h33ab790_3    conda-forge
libglib                   2.66.6               h8c8e623_3    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h02ac0ef_1012    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.37               h2a8f88b_0
libpq                     12.3                 h4f54205_3    conda-forge
librosa                   0.8.0              pyh9f0ad1d_0    conda-forge
librttopo                 1.1.0                h6a4060e_4    conda-forge
libsndfile                1.0.31               h0e60522_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             5.0.1                h37d8b57_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtheora                 1.1.1             h62dcd97_1004    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.2.0                h8ffe710_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
llvmlite                  0.35.0           py38h57a6900_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
loguru                    0.5.3            py38h32f6830_2    conda-forge
lxml                      4.6.2            py38h292cb97_1    conda-forge
lz4-c                     1.9.3                h2bbff1b_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.2                haa95532_0
matplotlib-base           3.3.2            py38hba9282a_0
mccabe                    0.6.1                    py38_1
meshio                    4.3.8              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.3              pyhd3eb1b0_0
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.2            py38hbd9d945_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy_extensions           0.4.3                    py38_0
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.1.2              pyhd3eb1b0_1
nest-asyncio              1.4.3              pyhd3eb1b0_0
netcdf4                   1.5.5.1         nompi_py38h5338a22_101    conda-forge
notebook                  6.2.0            py38haa244fe_0    conda-forge
numba                     0.52.0           py38h4c96930_0    conda-forge
numexpr                   2.7.2            py38hcbcaa1e_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0              pyhd3eb1b0_1
obspy                     1.2.2            py38h4b8e87e_0    conda-forge
olefile                   0.46                       py_0
openjpeg                  2.4.0                h48faf41_0    conda-forge
openpyxl                  3.0.5                      py_0    anaconda
openssl                   1.1.1j               h8ffe710_0    conda-forge
packaging                 20.8               pyhd3eb1b0_0
pandas                    1.2.1            py38hf11a4ad_0
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0    conda-forge
pathspec                  0.7.0                      py_0
pathtools                 0.1.2                      py_1
pcre                      8.44                 ha925a31_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.0            py38h4fa10fc_0
pip                       20.3.3           py38haa95532_0
pixman                    0.40.0               h8ffe710_0    conda-forge
pluggy                    0.13.1                   py38_0
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
poppler                   0.89.0               h3772339_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h0f1a9bc_3    conda-forge
proj                      7.1.1                h7d85306_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8                      py_0
psutil                    5.7.2            py38he774522_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pugixml                   1.11.4               h0e60522_0    conda-forge
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.7.4              pyhd3eb1b0_0
pylint                    2.6.0                    py38_0
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.0              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyproj                    2.6.1.post1      py38hbdc76b6_3    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
pytables                  3.6.1            py38h0abda79_3    conda-forge
python                    3.8.5                h5fd99cc_1
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.5             pyhd3eb1b0_0
pyvista                   0.28.1             pyhd8ed1ab_1    conda-forge
pyvistaqt                 0.3.0              pyhd8ed1ab_0    conda-forge
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.12.9               h5909a2a_3    conda-forge
qtawesome                 1.0.1                      py_0
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
rasterio                  1.2.0            py38h5653988_0    conda-forge
regex                     2020.11.13       py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
resampy                   0.2.2                      py_0    conda-forge
rope                      0.18.0                     py_0
rtree                     0.9.4            py38h21ff451_1
scikit-learn              0.23.2           py38h47e9c7a_0
scipy                     1.5.2            py38h14eb087_0
scooby                    0.5.6              pyh9f0ad1d_0    conda-forge
segyio                    1.9.3            py38h07472f2_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                51.3.3           py38haa95532_4
shapely                   1.7.1            py38h6953702_1    conda-forge
sip                       4.19.13          py38ha925a31_0
six                       1.15.0           py38haa95532_0
sniffio                   1.2.0            py38haa244fe_1    conda-forge
snowballstemmer           2.1.0              pyhd3eb1b0_0
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd3eb1b0_0
sphinx                    3.4.3              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.2.0            py38haa95532_0
spyder-kernels            1.10.1           py38haa95532_0
sqlalchemy                1.3.22           py38h294d835_1    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
sympy                     1.7.1            py38haa95532_0
tbb                       2020.2               h2d74725_3    conda-forge
tbb-devel                 2020.2               h2d74725_3    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.2            py38haa244fe_0    conda-forge
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
three-merge               0.1.1              pyhd3eb1b0_0
tiledb                    2.2.3                hf84e3da_0    conda-forge
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.55.1             pyhd3eb1b0_0
traitlets                 5.0.5                      py_0
transforms3d              0.3.1                      py_0    conda-forge
typed-ast                 1.4.2            py38h2bbff1b_1
typing_extensions         3.7.4.3                    py_0
ujson                     4.0.2            py38hd77b12b_0
urllib3                   1.26.2             pyhd3eb1b0_0
utfcpp                    3.1.2                         0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       9.0.1           no_osmesa_py38h4e85b29_103    conda-forge
watchdog                  0.10.4           py38haa95532_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.36.2             pyhd3eb1b0_0
win32_setctime            1.0.3                      py_0    conda-forge
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py38he774522_0
xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.3                ha925a31_3
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.8                h4e2f164_1    conda-forge```

**Comment by jorisvandenbossche** [comment] 2021-02-23 10:09
I think this is caused by a regression in GEOS 3.9.0, which is fixed in GEOS 3.9.1 (see https://lists.osgeo.org/pipermail/geos-devel/2021-February/010138.html  and https://github.com/libgeos/geos/issues/408). 

I indeed can reproduce it in an environment with GEOS 3.9.0, and it does no longer return empty linestrings in an environment with GEOS 3.9.1. 
And @Oi-sin's output of `conda list` also shows 3.9.0 is being used.

@Oi-sin I see you are using conda-forge. Shapely is normally already available for GEOS 3.9.1 as well, so if you do an update of those packages, the issue should be resolved.

**Comment by Oi-sin** [comment] 2021-02-23 12:14
Thank you. This looks like a logical explanation. 
Conda fails to update GEOS to 3.9.1. I'll have to wait until the dependend libraries have been updated too.

**Comment by jorisvandenbossche** [comment] 2021-02-23 14:43
Yes, the problem is that not yet all dependencies of geopandas are rebuilt with GEOS 3.9.1 support (eg GDAL/fiona -> https://github.com/conda-forge/libspatialite-feedstock/pull/64, and for pygeos I opened https://github.com/conda-forge/pygeos-feedstock/issues/31). If you don't need fiona, you should already be able to install Shapely itself with GEOS 3.9.1 support.

**Comment by jorisvandenbossche** [comment] 2021-03-05 11:58
In the meantime, all dependencies of geopandas should have been rebuilt with GEOS 3.9.1 on conda-forge

**Comment by jorisvandenbossche** [comment] 2021-03-05 12:55
So going to close this issue then, since it's fixed in GEOS 3.9.1.

**Comment by Oi-sin** [comment] 2021-03-05 12:56
Yeah \o/. Thanks for informing me of this update. I updated my environment and can no longer reproduce the bug. Thank you so much for your help.

**Closed by jorisvandenbossche** 2021-03-05 12:55 UTC
Labels: bug, needs info

**Comment by jorisvandenbossche** [comment] 2021-03-05 12:58
Good to hear!
