### ISSUE TITLE
BUG: `join` does not preserve geometry attribute

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#320] opened 2016-05-17 18:38 UTC
See line 487 of `geopandas.py` for example.

**Comment by jorisvandenbossche** [comment] 2016-05-17 22:39
This is actually maybe a duplicate of https://github.com/geopandas/geopandas/issues/247

**Comment by jorisvandenbossche** [comment] 2016-05-17 22:44
The example of `merge` you added in https://github.com/geopandas/geopandas/pull/301 will also not fully work (what you show will work, but further manipulations using `geometry` won't work)

**Comment by jorisvandenbossche** [comment] 2016-05-18 09:51
Duplicate of #247

**Closed by jorisvandenbossche** 2016-05-18 09:51 UTC
Labels: duplicate
