### ISSUE TITLE
BUG: `geopandas.read_file` does not appear to filter by bbox

### ISSUE THREAD

**Issue by krober10nd** [geopandas/geopandas#2253] opened 2021-12-04 15:02 UTC
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd 

fc = gpd.read_file('./Zone18_2014_01.gdb',layer='Zone18_2014_01_Broadcast', driver='OpenFileGDB', rows=slice(0, 10000))
print(fc)
bounds =fc.total_bounds
fc = gpd.read_file('./Zone18_2014_01.gdb',layer='Zone18_2014_01_Broadcast', driver='OpenFileGDB', rows=slice(0, 10000), bbox=tuple(bounds))
print(fc)
```

#### Problem description

I have a large geodatabase that I'd like to read in for only a relatively small area. However the `bbox` kwarg appears to not detect any intersection with the file. Changing the driver change the result neither does omitting the `rows` kwarg. 

The geodatabase has the CRS of 4326. 

Here is the output when I run the snippet above with my file. 
```
      SOG         COG  Heading    ROT               BaseDateTime  Status  VoyageID       MMSI ReceiverType  ReceiverID                    geometry
0     0.0  312.500000    511.0  128.0  2013-12-31T23:57:43+00:00       0         1  367707364            b  2003669982  POINT (-73.99592 40.40908)
1     0.0  302.899994    168.0    0.0  2013-12-31T23:57:43+00:00       0         2  338000781            b  2003669982  POINT (-74.15142 40.63913)
2     0.0  150.399994    511.0  128.0  2013-12-31T23:57:43+00:00       0         3  366984802            b  2003669982  POINT (-74.19375 40.64099)
3     1.7  221.800003    217.0  127.0  2013-12-31T23:57:43+00:00       0         4  367002803            b  2003669982  POINT (-74.06078 40.63553)
4     0.0  154.000000    511.0  128.0  2013-12-31T23:57:43+00:00       0         5  366003799            b  2003669982  POINT (-74.15196 40.69955)
...   ...         ...      ...    ...                        ...     ...       ...        ...          ...         ...                         ...
9995  0.0  340.000000    266.0    0.0  2014-01-01T00:51:47+00:00       5        64  367200010            b  2003669982  POINT (-74.07128 40.64310)
9996  0.0  267.000000    511.0  128.0  2014-01-01T00:51:47+00:00      15       118  367715705            b  2003669982  POINT (-74.13571 40.66586)
9997  0.0  278.700012    201.0    0.0  2014-01-01T00:51:47+00:00      15       122  367042136            b  2003669982  POINT (-74.19245 40.63890)
9998  2.8  163.399994    178.0    0.0  2014-01-01T00:51:47+00:00       0       116  366272503            b  2003669982  POINT (-73.75224 40.86567)
9999  0.0  188.100006    511.0  128.0  2014-01-01T00:51:49+00:00       0       195  367230705            b   003669984  POINT (-73.97244 40.70460)

[10000 rows x 11 columns]
(-77.321935, 40.36005, -73.114585, 45.643743)
Empty GeoDataFrame
Columns: [SOG, COG, Heading, ROT, BaseDateTime, Status, VoyageID, MMSI, ReceiverType, ReceiverID, geometry]
Index: []
```
#### Expected Output

I would expect `read_file` to detect the rows that intersect with the `bbox`. 

#### Output of ``geopandas.show_versions()``
>>> geopandas.show_versions()

SYSTEM INFO
-----------
python     : 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
executable : /usr/bin/python3.6
machine    : Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.6.2
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /home/krober/.local/lib/python3.6/site-packages/fiona/gdal_data
PROJ       : 7.2.1
PROJ data dir: /home/krober/.local/lib/python3.6/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.1.5
fiona      : 1.8.20
numpy      : 1.19.5
shapely    : 1.6.4.post2
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 2.2.5
mapclassify: None
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 6.0.0
pygeos     : None
>>>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by martinfleis** [comment] 2021-12-04 22:44
Hi, thanks for the report! I am not able to reproduce it with my files but I don't have any geodatabase at hand. Can you share some small gdb with which you see the same issue we can use for debugging?

Also, though it will probably not change much, can you try updating geopandas to 0.10.2?

**Comment by krober10nd** [comment] 2021-12-05 00:15
Hey, no problem. Thanks for the quick response.

Unfortunately I'm not able to shrink the data because I can't write in the GDB file format. In any case, it's a couple hundred  (~200 MB) and can be downloaded here:

https://coast.noaa.gov/htdata/CMSP/AISDataHandler/2014/01/Zone1_2014_01.zip

Its ship vessel pings, which are used heavily in coastal engineering projects.

https://marinecadastre.gov/ais/

Updating `geopandas` indeed didn't change the story.

**Comment by martinfleis** [comment] 2021-12-07 14:50
Thanks!

I can confirm that when you pass any bbox, `read_file` returns an empty geodataframe. However, the exactly same behaviour happens if I try to read the file with pyogrio, so I assume this is an issue with GDAL driver.

@brendan-ward do you have any what could be behind this?

**Comment by krober10nd** [comment] 2021-12-07 17:44
Thanks @brendan-ward FWIW I did this

```
ogr2ogr -clipsrclayer "Zone18_2014_01_BroadCast" -progress -f CSV  $file $f -clipsrc -73.96912 40.71540 -73.91484 40.74379 -lco GEOMETRY=AS_XY
```

which does appear to work. 

The operation speed varying significantly from file to file.

**Comment by rouault** [comment] 2022-11-10 03:48
This was a defect of the GDAL OpenFileGDB driver (probably of the dataset itself) that will be fixed per https://github.com/OSGeo/gdal/pull/6652. Do not hesitate to report upstream such issues.

**Comment by theroggy** [comment] 2023-03-09 11:54
I think this issue can be closed?

**Closed** 2023-03-09 19:32 UTC
Labels: bug, upstream issue
