### ISSUE TITLE
BUG:  plotting_with_geoplot example is broken

### ISSUE THREAD

**Issue by 2320sharon** [geopandas/geopandas#3220] opened 2024-03-13 21:18 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

Visit : https://geopandas.org/en/latest/gallery/plotting_with_geoplot.html and see the error messages
- this occurs on v:latest and v:stable

![image](https://github.com/geopandas/geopandas/assets/61564689/8b00dadc-77ef-49fd-b5a4-809b40fc57eb)

#### Problem description

The website should not be displaying these error messages.

**Comment by m-richards** [comment] 2024-03-14 12:09
Duplicate of #3103

**Closed as not planned** 2024-03-14 12:09 UTC
Labels: bug, needs triage
