### ISSUE TITLE
ENH: Support MySQL spatial

### ISSUE THREAD

**Issue by latot** [geopandas/geopandas#2445] opened 2022-06-02 19:22 UTC
Hi, actually there is ```to_postgis``` and other functions for postgres, I think would be great have this for MySQL too, it have spatial support too.

The actual ```to_postgis``` does not work with that db, is like obvs but I tested it anyway.

Thx.

**Comment by martinfleis** [comment] 2022-06-17 22:13
Duplicate of #2467

**Closed by martinfleis** 2022-06-17 22:13 UTC
Labels: enhancement

**Comment by latot** [comment] 2022-06-17 23:53
D: @martinfleis sorry!, I didn't found the issue, and even I forgot I made it! thx for closing it.
