### ISSUE TITLE
Reusing axes in GeoDataFrame.plot produces an empty figure

### ISSUE THREAD

**Issue by andrhua** [geopandas/geopandas#1214] opened 2019-11-20 17:19 UTC
I'm trying to draw a simple choropleth over NYC. The problem is that my target variable is counted on synthetic rectangle bins covering NYC, not the actual counties/boroughs, so in order to achieve that, first draw a NYC shapefile:
```
usa = gpd.read_file('shapefiles/gadm36_USA_2.shp')[['NAME_1', 'NAME_2', 'geometry']]
nyc = usa[usa.NAME_1 == 'New York']
ax = plt.axes([0, 0, 2, 2], projection=ccrs.PlateCarree())
ax.set_extent([-74.25559, -73.70001, 40.49612, 40.91553], ccrs.Geodetic())    
ax.add_geometries(nyc.geometry.values, 
                  ccrs.PlateCarree(),
                  facecolor='#1A237E');
```
![image](https://user-images.githubusercontent.com/15843809/69261092-04376b80-0bd2-11ea-8a9f-45b221d64a79.png)

Then add a choropleth:
```
gdf.plot(ax=ax, column='cnt',  cmap='inferno',  scheme='natural_breaks', k=10, legend=True)
```
results in this:

```<Figure size 432x288 with 0 Axes>```

However, drawing choropleth on its own axes works fine:

```gdf.plot(column='cnt', ...)```

![image](https://user-images.githubusercontent.com/15843809/69261398-8758c180-0bd2-11ea-9be6-c31999c9379b.png)

**Comment by martinfleis** [comment] 2019-11-20 21:31
Why are you plotting `nyc` GeoDataFrame this way? Following does not work for some reason?

```
ax = nyc.plot(facecolor='#1A237E')
gdf.plot(ax=ax, column='cnt',  cmap='inferno',  scheme='natural_breaks', k=10, legend=True)
```

**Comment by martinfleis** [comment] 2019-11-21 11:24
I see that the issue is now resolved on [SO](https://stackoverflow.com/questions/58945250/proper-reuse-of-axes-in-geodataframe-plot). Closing as there is nothing to do.

**Closed by martinfleis** 2019-11-21 11:24 UTC
