### ISSUE TITLE
BUG: Clip not return GeoDataFrame or GeoSeries

### ISSUE THREAD

**Issue by byander** [geopandas/geopandas#1649] opened 2020-10-06 17:05 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Example code to reproduce the bug

```python
import geopandas as gpd
from shapely.geometry import Polygon

GEOPACKAGE = r'C:\temp\test.gpkg'
crs = 31982

layer_name_mask = 'polygon_area'
layer_name_toclip = 'polygon_to_clip'


def create_polygons():
    polygon_data = Polygon([
        (581762.720, 7276585.620),
        (581762.720, 7186208.392),
        (490411.599, 7186208.392),
        (490411.599, 7276585.620)
    ])
    polygon_gpd = gpd.GeoDataFrame(geometry=[polygon_data])
    polygon_gpd.to_file(GEOPACKAGE, layer=layer_name_mask, crs=crs,
                        driver='GPKG')

    pol_to_clip_data = Polygon([
        (552576.412, 7214657.225),
        (552576.412, 7257625.935),
        (595472.170, 7257625.935),
        (595472.170, 7214657.225)
    ])
    pol_to_clip_gpd = gpd.GeoDataFrame(geometry=[pol_to_clip_data])
    pol_to_clip_gpd.to_file(GEOPACKAGE, layer=layer_name_toclip, crs=crs,
                            driver='GPKG')


if __name__ == '__main__':
    create_polygons()

    layer_mask = gpd.read_file(GEOPACKAGE, layer=layer_name_mask)
    layer_toclip = gpd.read_file(GEOPACKAGE, layer=layer_name_toclip)

    # Here not return data and/or any error
    results = gpd.clip(layer_toclip, layer_mask)
    print(results)
    results.to_file(GEOPACKAGE, layer='results', crs=crs, driver='GPKG')

```

#### Problem description

I was writing some  tests and I found this problem. If execute the code above, the expected output was a polygon results between the layer_mask and layer_toclip. 

For my real data the code works fine, but I don't sure I will have problems for future data. I tested with shapefile format and I haven't sucess too, but the both cases (from Geopackage and shapefile) I can success cliping in QGis software.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
executable : D:\Desenvolvimento\Python\vantia\backend\venv\Scripts\python.exe
machine    : Windows-10-10.0.17134-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.2
GDAL data dir: None
PROJ       : 7.0.1
PROJ data dir: D:\Desenvolvimento\Python\vantia\backend\venv\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.0
fiona      : 1.8.13
numpy      : 1.19.1
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None

</details>

**Comment by martinfleis** [comment] 2020-10-06 19:45
This is strange. I am not able to reproduce the issue, the GeoDataFrame is correctly clipped and saved in my case. What exactly is the issue here? `results` variable is empty?

**Comment by byander** [comment] 2020-10-06 20:19
Not exactly, the script only stops executing when trying the line:
`gpd.clip(layer_toclip, layer_mask)
`
No give error to check the reason.

**Comment by martinfleis** [comment] 2020-10-06 20:40
Stops executing? It hangs there or kills the kernel? How are you running the script?

**Comment by byander** [comment] 2020-10-06 20:44
I've been debugging and checked this line from file **clip.py**

`gdf_sub = gdf.iloc[gdf.sindex.query(poly, predicate="intersects")]

    # Clip the data with the polygon
    if isinstance(gdf_sub, GeoDataFrame):
        clipped = gdf_sub.copy()
        clipped["geometry"] = gdf_sub.intersection(poly)
    else:
        # GeoSeries
        clipped = gdf_sub.intersection(poly)

    return clipped`

For the example code above, most of time the script stops executation in the line gdf_sub, or when check the conditional.

For running the script, I created the file name.py with the code above and the console: python name.py
For debugging I'm using Pycharm.

**Comment by martinfleis** [comment] 2020-10-06 21:31
Can you show all the packages in your environment? Probably `pip list` since you are not using conda. It may be an issue with GEOS if it hangs on sindex.

**Comment by byander** [comment] 2020-10-06 23:43
Packages installed with pip. I don't use conda. I created a virtual environment with virtualenv. The packages Fiona, GDAL, rasteio and Rtree I donwloaded the wheels from Christopher Gohlke’s website.

```
$ pip list
Package         Version
--------------- -----------
affine          2.3.0
attrs           19.3.0
click           7.1.2
click-plugins   1.1.1
cligj           0.5.0
Fiona           1.8.13
GDAL            3.1.2
geopandas       0.8.1
memory-profiler 0.57.0
munch           2.5.0
numpy           1.19.1
pandas          1.1.0
pip             20.2.2
psutil          5.7.2
pyparsing       2.4.7
pyproj          2.6.1.post1
python-dateutil 2.8.1
python-decouple 3.3
pytz            2020.1
rasterio        1.1.5
Rtree           0.9.4
setuptools      49.3.2
Shapely         1.7.0
six             1.15.0
snuggs          1.4.7
wheel           0.34.2
```

**Comment by byander** [comment] 2020-10-07 12:53
I investigated further and I think that the problem can be Rtree package, when configuring the spatial index.

I created an example on Google Colab (Link below). 

When I execute the code in the first time the results from clip it's ok, but, I execute in the second time the same code, the kernel crash.

https://colab.research.google.com/drive/1zK7nBQ9bfYD62M-gXYmeGfZAlWzuu1uE?usp=sharing

**Comment by martinfleis** [comment] 2021-11-26 23:06
This seems to be fixed now, likely in rtree. The Colab notebook now works as expected even when executed second time. Feel free to reopen the issue if that is not the case.

**Closed by martinfleis** 2021-11-26 23:06 UTC
Labels: bug, needs triage
