### ISSUE TITLE
Geopandas cannot be installed on M1

### ISSUE THREAD

**Issue by jjcfrank** [geopandas/geopandas#1816] opened 2021-02-06 21:33 UTC
- [Yes] I have read the [documentation on installation](https://geopandas.org/install.html) and followed the instructions provided.

- [Yes] I have looked through [issues labeled "installation"](https://github.com/geopandas/geopandas/labels/installation) in the geopandas repo.

- If your issue is related to installation using the `conda-forge` channel, please open an issue in [geopandas-feedstock repository](https://github.com/conda-forge/geopandas-feedstock) instead.

---

#### System information

[what operating system do you have and what package management system are you
using]

MacOS BigSur on Apple chip M1

#### Environment details

<details>

I followed the installation steps from Geopandas docs, but got an error on last step (see below):

(gds) frankjimenez@franks-mbp ~ % conda install python=3 geopandas
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
geopandas -> pandas[version='>=0.23'] -> python[version='>=3.6|>=3.7|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
geopandas -> python[version='>=3.5']
python=3
Note that strict channel priority may have removed packages required for satisfiability.

(gds) frankjimenez@franks-mbp ~ % 

</details>

**Comment by martinfleis** [comment] 2021-02-06 21:39
Hmm, I don't really have a way to debug this. It is not surprising though. Have you tried specifying conda-forge channel (`-c conda-forge)`? My guess would be that it may be the only way to make it work at the moment.

To find out what the issue is, (if conda-forge won't solve it) I would need you to try installing dependencies one by one to figure out which one causes trouble (but based on the error, channels may resolve it).

**Comment by jjcfrank** [comment] 2021-02-06 21:44
I get the same issue with conda-forge channel:

(gds) frankjimenez@franks-mbp ~ % conda install -c conda-forge geopandas

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                         

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
Note that strict channel priority may have removed packages required for satisfiability.

(gds) frankjimenez@franks-mbp ~ %

**Comment by jjcfrank** [comment] 2021-02-06 21:45
Just checked: I cannot install Shapely, Fiona or Pyproj.

**Comment by martinfleis** [comment] 2021-02-06 21:51
Thanks. I guess that this needs to be resolved in the upstream then. My sense is that C dependencies of these libraries are not yet built for Apple silicon. Something like docker under rosetta2 may work in the meantime (just guessing)?

A relevant issue on shapely side https://github.com/Toblerity/Shapely/issues/1080.

**Comment by jjcfrank** [comment] 2021-02-06 21:58
> Something like docker under rosetta2 may work in the meantime

Good idea. Will try whilst something comes up. Thanks.

**Comment by chourmo** [comment] 2021-02-07 08:32
I am using GeoPandas (+pygeos) with a M1 MacBook Air, under rosetta 2 and miniforge without problems.

**Comment by tommylees112** [comment] 2021-02-08 21:32
How do you install python using Rosetta2 with miniforge?

**Comment by chourmo** [comment] 2021-02-09 17:42
This is kinda out of topic, but I installed everything the normal way (including geopandas), but you have to use a rosetta Terminal to ensure that everything is runned as x86. See https://www.youtube.com/watch?v=PnxlHfGdihI for how to it.

**Comment by jjcfrank** [comment] 2021-02-11 10:00
> This is kinda out of topic, but I installed everything the normal way (including geopandas), but you have to use a rosetta Terminal to ensure that everything is runned as x86.
> 
> See https://www.youtube.com/watch?v=PnxlHfGdihI for how to do it.

Does this work fine? I am wondering what will happen once these libraries are supported on the apple chip... will this mess things up?

**Comment by fabge** [comment] 2021-07-19 21:37
Any updates on getting it to work natively (without Rosetta)?
I can install `pandas`, `fiona`, `shapely` and `pyproj` separately.
It seems like `rtree` seems to be the culprit, this one cannot be found as conda package compiled for ARM...

**Comment by martinfleis** [comment] 2021-07-19 21:45
@fabge it is a bit out of our hands now. GeoPandas itself is pure Python and we need our dependencies to be compiled. `pygoes` should be available. Can you try installing that instead of `rtree`? With pygeos in your environment, rtree is not used.

**Comment by fabge** [comment] 2021-07-20 05:59
Thanks for the quick reply! Unfortunately this didn't help, the installation still fails.
What's weird is that there is no information given on what exactly fails. Below is the error when `pygeos` is pre-installed.

```bash
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

This one is the error in a vanilla conda env:

```bash
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError:
```

**Comment by martinfleis** [comment] 2021-07-20 08:06
This is indeed strange. I don't have access to the M1 machine so can't really help much I am afraid.

**Comment by fabge** [comment] 2021-07-20 10:49
Quick update: I made it work by installing [from source](https://geopandas.org/getting_started/install.html#installing-from-source). After installing the necessary packages with conda and installing `geopandas` with pip, the package can be used.

> With pygeos in your environment, rtree is not used.

The important difference (from @martinfleis) is to conda install `pygeos` instead of `rtree`, as `rtree` is not available natively on M1 macs.

**Comment by mauriciodinamarca** [comment] 2021-07-21 02:08
> Quick update: I made it work by installing [from source](https://geopandas.org/getting_started/install.html#installing-from-source). After installing the necessary packages with conda and installing `geopandas` with pip, the package can be used.
> 
> > With pygeos in your environment, rtree is not used.
> 
> The important difference (from @martinfleis) is to conda install `pygeos` instead of `rtree`, as `rtree` is not available natively on M1 macs.

Could you add a simple procedure for trying? Did the same thing as you said and it didnt work 😢 
`conda install pandas fiona shapely pyproj pygeos`
`conda install geopandas`
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
`
``

**Comment by FelipeRocha** [comment] 2021-07-21 14:21
> > Quick update: I made it work by installing [from source](https://geopandas.org/getting_started/install.html#installing-from-source). After installing the necessary packages with conda and installing `geopandas` with pip, the package can be used.
> > > With pygeos in your environment, rtree is not used.
> > 
> > 
> > The important difference (from @martinfleis) is to conda install `pygeos` instead of `rtree`, as `rtree` is not available natively on M1 macs.
> 
> Could you add a simple procedure for trying? Did the same thing as you said and it didnt work 😢
> `conda install pandas fiona shapely pyproj pygeos`
> `conda install geopandas`
> 
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: /
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> `
> ``
> ```

try `pip install git+git://github.com/geopandas/geopandas.git` instead of `conda install geopandas`

**Comment by martinfleis** [comment] 2021-07-21 14:51
If you have all required dependencies installed and working, then `pip install` is a safe option. Even `pip install geopandas` may work. I'd assume there is no need for installing from git.

**Comment by fabge** [comment] 2021-07-21 20:00
Exactly, try to install geopandas with `pip install` @mauriciodinamarca.
The complete installation process would then look like:
```bash
conda install pandas fiona shapely pyproj rtree
pip install geopandas
```
(or `pip install git+git://github.com/geopandas/geopandas.git` - both should work)

**Comment by LiamBui** [comment] 2021-09-01 21:11
I was having trouble running the above steps. What worked for me was to `brew install gdal proj` and then run 
```pip install geopandas```
Hope this may help someone later on.

**Comment by themrcesi** [comment] 2021-09-23 12:24
> I was having trouble running the above steps. What worked for me was to `brew install gdal proj` and then run
> `pip install geopandas`
> Hope this may help someone later on.

This has also worked for me!

**Comment by givemetarte** [comment] 2021-10-17 12:18
> I was having trouble running the above steps. What worked for me was to `brew install gdal proj` and then run
> `pip install geopandas`
> Hope this may help someone later on.

This worked for me, too! Thanks 😘

**Comment by jreakin** [comment] 2021-12-29 22:20
> I was having trouble running the above steps. What worked for me was to `brew install gdal proj` and then run `pip install geopandas` Hope this may help someone later on.

You're a lifesaver! Worked perfectly.

**Comment by martinfleis** [comment] 2021-12-30 16:13
At the moment, installing geopandas on M1 macs is no longer an issue and can be achieved via conda or pip+homebrew. See the summary below. Keep in mind that a lot of comments from the thread above are no longer true.

GeoPandas itself is written in pure Python, so there is no issue running that on any architecture. However, it depends on other libraries that are written in other languages (C, C++) that need to be compiled specifically for M1 chips. While you could compile it yourself, I am not going to cover this option as it is not user friendly.

There are three possible sources of required libraries - pip wheels, conda-forge, and Homebrew.

When a Python package requires C dependency, it can create wheels with the dependency compiled for each system and chip architecture. See for example pygeos - https://pypi.org/project/pygeos/#files. What you need is `*macosx_11_0_arm64.whl `. If your package doesn't offer it, you have to find another way of installing than `pip`. Since  GeoPandas requires shapely and fiona (among others) that do not have these wheels, you should look elsewhere - either on conda-forge or Homebrew. Below are both options tested as of today.

## Conda and conda-forge way (recommended)

Conda-forge currently has all packages geopandas needs

Install M1 version of miniforge or mambaforge. It can be downloaded from here - https://github.com/conda-forge/miniforge.

```shell
conda install -c conda-forge geopandas pygeos
```
Note: if you install x86 (Intel) version of conda, it will run under Rosetta2 and install all packages using x86 architecture, meaning that everything will run under emulation. Try to avoid that.

## Pip and Homebrew way

Homebrew can install C libraries compiled for M1. Python packages will find and use them.

Using an environment with Python 3.9

Install shapely:

```shell
brew install geos
export DYLD_LIBRARY_PATH=/opt/homebrew/opt/geos/lib/
pip install shapely
```
`DYLD_LIBRARY_PATH` is needed for shapely to find GEOS installation.

Install fiona:
```
brew install gdal
pip install fiona
```
Install pyproj:
```
brew install proj
pip install pyproj
```

Install geopandas and pygeos for speedups:
```shell
pip install pygeos
pip install geopandas
```

With all that, I am going to close the issue.

**Closed by martinfleis** 2021-12-30 16:13 UTC
Labels: installation

**Comment by StevenLi-DS** [comment] 2022-08-14 23:51
@martinfleis 
It doesn't seem like geopandas has a `osx-arm64` label on conda-forge. Am I missing something?
https://anaconda.org/conda-forge/geopandas
![image](https://user-images.githubusercontent.com/33796896/184559420-be34067a-03e8-4588-b488-6214bd112928.png)

**Comment by m-richards** [comment] 2022-08-15 02:36
@StevenLi-DS (I'm not across the M1 packaging situation particularly closely) I think the noarch install is all you need - geopandas itself is pure python, it just has compiled dependencies, note that the linux/ windows / osx specific architecture versions are for v0.3 which is well out of date.
