### ISSUE TITLE
BUG: segfault when running `shapely.ops.unary_union` on GeoSeries (0.10.1)

### ISSUE THREAD

**Issue by bretttully** [geopandas/geopandas#2171] opened 2021-10-13 06:33 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import pygeos
import shapely
import shapely.wkt
from shapely.ops import unary_union

print(f"{gpd.__version__=}")
print(f"{pygeos.__version__=}")
print(f"{shapely.__version__=}")

polys = ['POLYGON ((366 116, 360 121, 359 131, 344 145, 346 155, 336 161, 335 173, 320 177, 320 186, 315 191, 315 203, 300 209, 295 234, 288 237, 281 233, 272 233, 265 239, 269 247, 267 257, 270 265, 260 272, 261 283, 251 288, 255 294, 254 301, 237 304, 230 309, 223 308, 216 313, 207 309, 202 314, 191 314, 182 324, 170 326, 159 325, 151 317, 150 309, 154 305, 154 297, 157 293, 171 288, 171 279, 174 275, 211 272, 207 267, 207 261, 212 256, 210 247, 216 241, 217 235, 224 232, 227 226, 218 219, 221 209, 214 204, 216 193, 205 189, 201 181, 193 181, 189 187, 177 188, 171 195, 153 196, 139 207, 139 215, 133 223, 132 231, 124 241, 118 244, 107 243, 96 237, 91 224, 84 223, 80 215, 73 214, 66 204, 59 204, 51 192, 41 187, 37 175, 28 167, 28 159, 23 154, 24 147, 32 143, 33 135, 55 113, 55 89, 61 82, 57 72, 58 59, 69 50, 71 43, 74 40, 82 40, 88 34, 98 34, 102 22, 129 22, 134 17, 137 6, 155 2, 203 2, 213 5, 221 16, 242 19, 313 18, 327 34, 344 37, 352 42, 359 83, 363 89, 362 103, 366 116), (261 177, 257 171, 250 176, 253 181, 251 193, 255 196, 261 193, 258 188, 261 177))', 'POLYGON ((206 268, 199 273, 182 272, 173 263, 174 250, 186 248, 189 258, 203 259, 206 268))']
polys = [shapely.wkt.loads(p) for p in polys]

shapely_uu = unary_union(polys)
print(f"{shapely_uu.is_valid=}")

gs = gpd.GeoSeries(polys)
gs_uu = gs.unary_union
print(f"{gs_uu.is_valid=}")

# this line segfaults where it didn't with 0.9.0 (and no pygeos)
unary_union(gs)
```

Gives
```
gpd.__version__='0.10.1'
pygeos.__version__='0.10.2'
shapely.__version__='1.7.1'
shapely_uu.is_valid=True
gs_uu.is_valid=True
Segmentation fault
```

#### Problem description

Code that ran with geopandas 0.9 now segfaults with geopandas 0.10.1 + pygeos 0.10.2

#### Expected Output

I'm not sure if we should expect this to work or not, but I didn't expect a segfault

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0]
executable : /opt/conda/envs/pyai/bin/python
machine    : Linux-5.10.47-linuxkit-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /opt/conda/envs/pyai/lib/libgeos_c.so
GDAL       : 3.3.1
GDAL data dir: /opt/conda/envs/pyai/share/gdal
PROJ       : 8.0.1
PROJ data dir: /opt/conda/envs/pyai/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.1
pandas     : 1.3.3
fiona      : 1.8.20
numpy      : 1.21.2
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.2.1
matplotlib : 3.4.3
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 5.0.0
pygeos     : 0.10.2

</details>

**Comment by jorisvandenbossche** [comment] 2021-10-13 07:02
@bretttully Thanks for the report!

> Code that ran with geopandas 0.9 now segfaults with geopandas 0.10.1 + pygeos 0.10.2

I can actually reproduce this with geopandas 0.9 as well, so I suppose you didn't have pygeos installed in your environment with geopandas 0.9? 

It seems some bad interactions between pygeos and shapely. But it's a bit strange: if you do `unary_union(list(gs))` instead of ``unary_union(gs)`` then it works. But this `list(..)` iterates over the geoseries, which is what shapely also does under the hood in the `unary_union` operation ..

**Comment by bretttully** [comment] 2021-10-13 07:10
That's right, I'm only just playing around with pygeos with this new release. I'll try and do some digging too, see if I can find anything useful.

**Comment by jorisvandenbossche** [comment] 2021-10-13 07:29
Basically what happens when passing a GeoSeries with pygeos geometries under the hood is the following:

```
In [2]: arr = gs.array.data

In [3]: arr
Out[3]: 
array([<pygeos.Geometry POLYGON ((366 116, 360 121, 359 131, 344 145, 346 155, 336 ...>,
       <pygeos.Geometry POLYGON ((206 268, 199 273, 182 272, 173 263, 174 250, 186 ...>],
      dtype=object)

In [4]: import shapely.geometry
   ...: import shapely.geos

In [5]: def to_shapely(geom):
   ...:     geom = shapely.geos.lgeos.GEOSGeom_clone(geom._ptr)
   ...:     return shapely.geometry.base.geom_factory(geom)

In [6]: geoms = [to_shapely(arr[0]), to_shapely(arr[1])]

In [7]: unary_union(geoms)
Out[7]: <shapely.geometry.polygon.Polygon at 0x7f78e12d69a0>
```

But so that doesn't segfault, while `unary_union(gs)` does. Maybe it is something with the lifetime of the Shapely / GEOS geometries.

**Comment by jorisvandenbossche** [comment] 2021-10-13 07:41
Further mimicking the implementation:

```python
# pygeos to shapely conversion function
import shapely.geometry
import shapely.geos

def to_shapely(geom):
    geom = shapely.geos.lgeos.GEOSGeom_clone(geom._ptr)
    return shapely.geometry.base.geom_factory(geom)

# shapely's unary_union function
from ctypes import c_void_p
from shapely.geometry.base import geom_factory
from shapely.geos import lgeos

def unary_union(geoms):
    L = len(geoms)
    subs = (c_void_p * L)()
    for i, g in enumerate(geoms):
        subs[i] = g._geom
    collection = lgeos.GEOSGeom_createCollection(6, subs, L)
    return geom_factory(lgeos.methods['unary_union'](collection))

# variant of unary_union that mimicks the conversion from pygeos->shapely on the fly
def unary_union2(geoseries):
    L = len(geoseries)
    subs = (c_void_p * L)()
    for i, g in enumerate(geoseries.array.data):
        subs[i] = to_shapely(g)._geom
    collection = lgeos.GEOSGeom_createCollection(6, subs, L)
    return geom_factory(lgeos.methods['unary_union'](collection))

# this works
arr = gs.array.data
geoms = [to_shapely(arr[0]), to_shapely(arr[1])]
unary_union(geoms)

# this segfaults
unary_union2(gs)
```

**Comment by jorisvandenbossche** [comment] 2021-10-13 07:53
cc @caspervdw

**Comment by jorisvandenbossche** [comment] 2021-10-13 20:10
> Now, if we cannot get this to work reliably, we should maybe always go through WKB in the pygeos->shapely conversion.

Quickly trying this, and that actually still results in the segfault .. So it seems we can't solve this from the geopandas side, but is caused by how shapely iterates over the sequence with geometries, and collects only the pointers in the for loop (and thus not keeping track of the loop variables, assuming those are the same shapely geometries as in the sequence).

**Comment by jorisvandenbossche** [comment] 2024-01-05 13:23
Given that pygeos is no longer maintained and shapely 2.0 is now well established, and that the main dev branch of geopandas (for 1.0) only supports shapely > 2 (so no longer any issues with mixing pygeos and shapely are possible), I think we can close this issue.

**Closed by jorisvandenbossche** 2024-01-05 13:23 UTC
Labels: bug
