### ISSUE TITLE
REGR: indexing doesn't return geometry but Series if geometry is only column

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2282] opened 2022-01-03 10:45 UTC
One of the recent PRs caused a regression in indexing. If there's a single column in a GeoDataFrame, indexing using `df.loc[0].geometry` returns a Series instead of a shapely geometry (as it did before).

```py
import geopandas
df = geopandas.read_file(geopandas.datasets.get_path("nybb"))
df[["geometry"]].loc[0].geometry

geometry    MULTIPOLYGON (((970217.022 145643.332, 970227....
Name: 0, dtype: geometry
```

On 0.10.2:

```py
import geopandas
df = geopandas.read_file(geopandas.datasets.get_path("nybb"))
df[["geometry"]].loc[0].geometry

<shapely.geometry.multipolygon.MultiPolygon at 0x107377e50>
```

If there are other columns apart from geometry, it correctly returns the shapely geometry.

@m-richards I haven't looked in detail but I think it is caused by #2060, there was no other commit relevant to this.

**Comment by m-richards** [comment] 2022-01-03 11:21
It's most likely that then since it did mess with indexing, I should have a chance to look into this tomorrow sometime.

**Comment by jorisvandenbossche** [comment] 2022-01-03 13:59
So the reason this changed is because we now try to return a GeoSeries for `df.loc[0]`. We do this in general when getting a Series out of the GeoDataFrame (through `_constructor_sliced` which was added in #2060). For getting a column as Series, this makes sense. But when getting a row, it probably is not that useful to do this ..

And because `df.loc[0]` now returns a GeoSeries if all elements of the row are geometries, `df.loc[0].geometry` then returns the same GeoSeries instead of getting the single element of the series with label "geometry" (because a GeoSeries has a `geometry` attribute which has priority over checking the index labels). 

(general workaround is to use `["geometry"]` instead of `.geometry` for label-based access, which is in general more robust)

---

For a solution, the main problem is that `_constructor_sliced` is not "aware" of whether is was used to create a row or a column, I think. So either we live with this change in behaviour, or we need to find another way to fix the cases for which we added `_constructor_sliced` (or live with reverting this specific fix). 

One example that fixed this was doing `df.iloc[:, 4]` in case that returns a geometry column (previously that returned a Series, now a GeoSeries).

That could also be fixed by overriding `iloc` (as we already do for `__getitem__` as well, although for `iloc` that would be more complicated)

**Comment by m-richards** [comment] 2022-01-04 01:33
> That could also be fixed by overriding iloc (as we already do for __getitem__ as well, although for iloc that would be more complicated)

I'd like to avoid this if possible, because if this series of changes (the fixes to #2060, #2080, or the new version of it I haven't written) and #2280) it should be possible to remove the overload of getitem completely (I think) and have everything consistently handled by `_constructor` - it'd be nice to have this logic all in one place.

Regarding the cases in which `_constructor_sliced` is used for, removing `_constructor_sliced` on main, only squeeze and iloc tests fail - and squeeze uses iloc internally.
In the squeeze case, we get a Series of geometrydtype with the correct name (but crs is obviously no longer retained).

And the iloc case is for using iloc to access a single column and getting a GeoSeries, which is the 
>One example that fixed this was doing df.iloc[:, 4] in case that returns a geometry column (previously that returned a Series, now a GeoSeries).
case Joris described above.

Given that, the choices are back to overloading iloc, or making `_constructor_sliced` more strict - along the lines of if the series is has dtype GeometryDType I think(?), in any case I think that's a starting point.

**Comment by m-richards** [comment] 2022-01-04 01:51
A more fundamental question, why does `GeoSeries` have a `geometry` in the first place? - the attribute that's now present because `df[["geometry"]].loc[0]` is a geoseries and is causing this issue. Obviously it's useful to be able to pick the active geometry column off a dataframe, but for a series, it's just aliasing the object itself. I can see an argument that it lets one write generic code that could recieve a geoseries or a geodataframe, but on the other hand, things like `sjoin` only work on dataframes (if I recall correctly).

**Comment by jorisvandenbossche** [comment] 2022-01-31 09:01
> Edit: Doing that won't solve the singleton column case, I was doing something along the lines of
> ...
> but this would then break consistency for length one dataframes (how would we distinguish a "row" vs a dataframe of length 1?

Is the `and srs.shape != (1,):` part needed for solving the row access case? I would have expected that pandas would pass an object array if selecting a single row from a DataFrame. Or does it actually pass a geometry array if there is only a single column (or single dtype) in the DataFrame? (it might do that to try to preserve the dtype)

**Comment by m-richards** [comment] 2022-01-31 09:58
>Is the and srs.shape != (1,): part needed for solving the row access case?

I might be misinterpretting what you're asking here.
On the main branch right now, if I select a single column the dtype is presevered - same as Martin's original example:
```python
In [1]: import geopandas
In [2]: df = geopandas.read_file(geopandas.datasets.get_path("nybb"))
In [3]: type(df.head(1).iloc[:, -1])
Out[3]: geopandas.geoseries.GeoSeries
In [5]: df.head(1)
Out[5]:
   BoroCode       BoroName     Shape_Leng    Shape_Area                                           geometry
0         5  Staten Island  330470.010332  1.623820e+09  MULTIPOLYGON (((970217.022 145643.332, 970227....

In [6]: df.head(1).dtypes
Out[6]:
BoroCode         int64
BoroName        object
Shape_Leng     float64
Shape_Area     float64
geometry      geometry
dtype: object
```
and dtypes are also preserved - so pandas doesn't do anything special with the row case as far as I can tell (the dtype is also preserved on 0.10.2, it's just wrapped up in a series rather than a geoseries. 

But this is only if geometry is the only column, if we just slice the first row, with multiple columns

```
In [14]: type(df.loc[0])
Out[14]: pandas.core.series.Series

In [15]: type(df[['geometry']].loc[0])
Out[15]: geopandas.geoseries.GeoSeries
```
which might be what you were expecting to see?

**Comment by jorisvandenbossche** [comment] 2022-01-31 10:20
For exploring, I added a print statement in `_geoseries_constructor_with_fallback` (used in `GeoSeries._constructor` and `GeoDataFrame._constructor_sliced`), and then using the example code of the comment above, I see (using current main):

```
In [4]: df.iloc[:, -1]

Data passed to _geoseries_constructor_with_fallback: 
SingleBlockManager
Items: RangeIndex(start=0, stop=5, step=1)
ExtensionBlock: 5 dtype: geometry
Out[4]: 
0    MULTIPOLYGON (((970217.022 145643.332, 970227....
1    MULTIPOLYGON (((1029606.077 156073.814, 102957...
2    MULTIPOLYGON (((1021176.479 151374.797, 102100...
3    MULTIPOLYGON (((981219.056 188655.316, 980940....
4    MULTIPOLYGON (((1012821.806 229228.265, 101278...
Name: geometry, dtype: geometry
```

So when selecting a single column, you get an object (in this case a SingleBlockManager) that already has a `geometry` dtype.

When selecting a row:

```
In [5]: df.iloc[0, :]

Data passed to _geoseries_constructor_with_fallback: 
[5 'Staten Island' 330470.010332 1623819823.81
 <shapely.geometry.MultiPolygon MULTIPOLYGON (((970217.0223999023 145643.33221435547,...>]
Out[5]: 
BoroCode                                                      5
BoroName                                          Staten Island
Shape_Leng                                        330470.010332
Shape_Area                                        1623819823.81
geometry      MULTIPOLYGON (((970217.0223999023 145643.33221...
Name: 0, dtype: object
```

you see that it gets passed a python list, so not an object with geometry dtype. 

In this case, this list is also containing non-geometry values, so trying to create a GeoSeries from this will raise an error, so ``_geoseries_constructor_with_fallback`` will fall back to a Series.


However, if there is only a single column:
```
In [7]: sub = df[["geometry"]]
...

In [9]: sub.iloc[0]

Data passed to _geoseries_constructor_with_fallback: 
<GeometryArray>
[<shapely.geometry.MultiPolygon MULTIPOLYGON (((970217.0223999023 145643.33221435547, ...>]
Length: 1, dtype: geometry
Out[9]: 
geometry    MULTIPOLYGON (((970217.022 145643.332, 970227....
Name: 0, dtype: geometry
```

pandas indeed passes a GeometryArray, and not a python list. So that's as I "feared" above (well, it's somewhat logical from pandas' point of view), and is the reason that the "strict" fallback doesn't help for the single-geometry-column case.

But it would still help in general to avoid corner cases. For example, assume you have multiple columns, but the other values for the non-geometry columns happen to be missing for the row you are selecting:

```
df.loc["Shape_Leng", 0] = np.nan
sub = df[["Shape_Leng", "geometry"]]

In [20]: sub.iloc[0]

Data passed to _geoseries_constructor_with_fallback: 
[nan
 <shapely.geometry.MultiPolygon MULTIPOLYGON (((970217.0223999023 145643.33221435547, ...>]
Out[20]: 
Shape_Leng                                                 None
geometry      MULTIPOLYGON (((970217.022 145643.332, 970227....
Name: 0, dtype: geometry

In [21]: type(_)
Out[21]: geopandas.geoseries.GeoSeries
```

So the above also returns a GeoSeries, while this should return a pd.Series (only because the other values was missing, the `_geoseries_constructor_with_fallback` didn't fall back to Series)

**Comment by m-richards** [comment] 2022-01-31 12:29
Well that way of looking at things is a lot more insightful. So it looks like perhaps this could work as a solution solving this specific regression? by inspecting the data argument to constructor_sliced, rather than the series built from it (which seems obvious in hindsight).

Will have another look at this again and see if I get a little further without getting stuck, thanks for the fresh insight.

**Comment by jorisvandenbossche** [comment] 2022-05-21 11:19
> A more fundamental question, why does `GeoSeries` have a `geometry` in the first place? ... Obviously it's useful to be able to pick the active geometry column off a dataframe, but for a series, it's just aliasing the object itself. I can see an argument that it lets one write generic code that could recieve a geoseries or a geodataframe, but on the other hand, things like `sjoin` only work on dataframes (if I recall correctly).

Yes, it's certainly not super useful for direct interactive use. But I suppose the reason is exactly that: being able to write code more easily that works on the geometry data from either GeoDataFrame or GeoSeries. And as you mention, we actually do that internally in our code base. 

Personally, I am not attached to this attribute for GeoSeries, but I am also not sure it is worth the trouble to deprecate it / eventually remove it. 
(in any case, I would consider this as a separate discussion, and not as a potential way to fix this specific regression, as mentioned in https://github.com/geopandas/geopandas/pull/2332#issuecomment-1133602175)

**Closed** 2022-06-04 10:33 UTC
Labels: regression
