### ISSUE TITLE
GeoPandas to_file() saves GeoDataFrame without coordinate system

### ISSUE THREAD

**Issue by AlexArcPy** [geopandas/geopandas#363] opened 2016-08-03 05:56 UTC
I have

```
    GeoPandas 0.2.1 py27_0
    fiona 1.7.0 np110py27_1
    Python 2.7.10
```

installed in `Anaconda 2-4.1.1-Windows-x86` environment. I am able to construct `GeoDataFrame` by reading input datasets and operate the data yet saving an output dataset does not preserve the coordinate system.

```
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.to_file(driver='ESRI Shapefile',filename=r'C:\GIS\Temp\world_out.shp')
```

The `world_out.shp` does contain the features and the schema of the source shapefile, but coordinate system is `undefined (<Unknown>)`. The `world_out.prj` file is 0 KB and doesn't contain anything.

```
out = gpd.read_file(r'C:\GIS\Temp\world_out.shp')
print out.crs
>>> {}
```

I have tested to perform this operation using pure `Fiona` and it works fine, preserving the `crs` information.

So, it seems as `GeoPandas` is not able to write `crs` of the GeoDataFrame into the output dataset when calling the `to_file()` method. I have tried calling `to_file()` on GeoDataFrames constructed from various sources and datasets and the coordinate system information was never present in the output dataset.

What am I doing wrong or is it a bug?

**Comment by mullenkamp** [comment] 2016-12-21 03:08
I also have this problem...

**Comment by jdmcbr** [comment] 2017-01-04 05:42
I wasn't able to reproduce this error (Windows 10, same python/geopandas/fiona versions above). Could you try the following in the anaconda prompt? This will create a virtual environment with clean installs of everything, and won't affect the rest of your system.

    conda create -n gpdtest python=2.7.10 geopandas=0.2.1 fiona=1.7.0
    conda activate gpdtest
    
Then just start python and try your test again.

**Comment by AlexArcPy** [comment] 2017-01-04 10:07
@jdmcbr , thanks for posting. From which channel do you install geopandas and fiona? They are not present in the default conda channel.

```
Error: Packages missing in current win-32 channels:
  - geopandas 0.2.1*
  - fiona 1.7.0*
```

Perhaps different builds result in different behavior.

**Comment by jorisvandenbossche** [comment] 2017-01-04 10:12
@AlexArcPy You can try from `conda-forge`:

```
conda install geopandas -c conda-forge
```

**Comment by jdmcbr** [comment] 2017-01-04 16:12
@AlexArcPy Oops, yes, I have my default channel set to `conda-forge`, and I assumed you did too based on the package versions you posted.

**Comment by mullenkamp** [comment] 2017-01-04 21:24
I think I've found my problem. 
If I create a geopandas from x and y coordinates using the loads function from shapely and define the coordinate system as described in the [manual](http://geopandas.org/projections.html#setting-a-projection), the export from to_file does not populate the prj file.
But if I load in a shapefile from the read_file function and export that object, then it does properly create a prj file.

**Comment by jorisvandenbossche** [comment] 2017-01-04 21:37
> Now it's just a matter of figuring out how to convert an epsg number into a crs dictionary that geopandas knows how to export to a prj file...

You can just pass the epsg number: `my_geoseries.crs = {'init' :'epsg:4326'}` (see the doc link you provided). 
Or is it this way that it is not working?

**Comment by mullenkamp** [comment] 2017-01-04 21:43
That's what's not working...
Here's the "good" dictionary (exports a shapefile properly): 
{u'ellps': u'GRS80',
 u'k': 0.9996,
 u'lat_0': 0,
 u'lon_0': 173,
 u'no_defs': True,
 u'proj': u'tmerc',
 u'units': u'm',
 u'x_0': 1600000,
 u'y_0': 10000000}

Also...after a bit more testing...converting the projection of the "good" geopandas object using to_crs(epsg=2193) (the same projection actually), then trying to export it to a shapefile crashes python.

**Comment by jorisvandenbossche** [comment] 2017-01-04 21:46
Both should be considered as bugs (and I used `to_file` correctly a lot after using `to_crs(epsg=2193)`), so could you provide a small reproducible example?

In any case, it would also be nice to have a small utility function to convert epsg numbers to its full dict (and the other way around if possible).

**Comment by mullenkamp** [comment] 2017-01-04 22:20
Certainly!
[working_export.zip](https://github.com/geopandas/geopandas/files/686000/working_export.zip)

I'm using the most up-to-date packages from conda-forge
geopandas = 0.2.1
fiona = 1.7.1.post1
shapely = 1.5.17.post1

`from geopandas import read_file, GeoDataFrame
from fiona import crs
from shapely.geometry import Point

t1 = read_file('working_export.shp')
t1.crs
t1.to_file('test1.shp')  # This should produce a proper prj file

t2 = t1.to_crs(epsg=2193)
t2.to_file('test2.shp') # Crashes python

x = t1.geometry.apply(lambda p: p.x).values
y = t1.geometry.apply(lambda p: p.y).values
geometry = [Point(xy) for xy in zip(x, y)]
df = GeoDataFrame(t1['site'], geometry=geometry, crs=crs.from_epsg(epsg))
df.to_file('test3.shp')  # Crashes python too!`

Thanks for your help!

**Comment by jorisvandenbossche** [comment] 2017-01-04 22:29
Hmm, working for me:

```
In [71]: t1 = read_file('../Downloads/working_export/working_export.shp')

In [73]: t1.crs
Out[73]: 
{'ellps': 'GRS80',
 'k': 0.9996,
 'lat_0': 0,
 'lon_0': 173,
 'no_defs': True,
 'proj': 'tmerc',
 'units': 'm',
 'x_0': 1600000,
 'y_0': 10000000}

In [77]: t2 = t1.to_crs(epsg=2193)

In [78]: t2.crs
Out[78]: {'init': 'epsg:2193', 'no_defs': True}

In [79]: t2.to_file('test2.shp')

In [80]: read_file('test2.shp').crs
Out[80]: 
{'ellps': 'GRS80',
 'k': 0.9996,
 'lat_0': 0,
 'lon_0': 173,
 'no_defs': True,
 'proj': 'tmerc',
 'units': 'm',
 'x_0': 1600000,
 'y_0': 10000000}
```

content of the test2.proj file:
```
PROJCS["NZGD2000_New_Zealand_Transverse_Mercator_2000",GEOGCS["GCS_NZGD_2000",DATUM["D_NZGD_2000",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",173],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",1600000],PARAMETER["false_northing",10000000],UNIT["Meter",1]]
```

Using the exact same versions (on linux ubuntu).

**Comment by mullenkamp** [comment] 2017-01-04 22:39
Oh great...I have to use Windows (7) at work...even though I use Ubuntu at home...
Why would this cause a problem?

**Comment by mullenkamp** [comment] 2017-01-05 00:06
For future reference, [PyCRS](https://github.com/karimbahgat/PyCRS) is able to convert an epsg number to a full proj4 string that works with geopandas/fiona.

**Comment by jdmcbr** [comment] 2017-01-05 03:56
@mullenkamp Likewise, I tested in a conda environment on a Windows 10 computer and was able to run your example without any problems. Could you try creating a test environment, like the example above, and see if you get the same behavior? Or perhaps you already did that?

**Comment by mullenkamp** [comment] 2017-01-05 18:50
Interesting...the test environment does work...thanks for pointing me to that.
So how can I solve this problem? Should I uninstall and reinstall python and all packages?

**Comment by jdmcbr** [comment] 2017-01-05 20:30
I would start by doing `conda list` both inside and outside of the test environment and checking to see if there are any differences in package versions. While conda mostly does a good job of managing package dependencies, I've run into issues sometimes where some of the C/C++ dependencies of geospatial packages are not handled properly unless they are installed altogether. That is, installing packages with something like

    conda install shapely fiona geopandas

rather than

    conda install fiona
    conda install shapely
    conda install geopandas

**Comment by ResidentMario** [comment] 2017-03-09 04:16
Also, AFAIK pinned version of `gdal` get moved from time to time, but it takes a little while for the rest of the tools on `conda` to catch up. This causes time-sensitive inconsistencies like this to crop up occasionally, which fail to reproduce when you do the same thing later.

**Comment by rutgerhofste** [comment] 2017-08-28 18:55
Does is matter if your GDAL_DATA variable is set correctly, can you try:
```
import os
if 'GDAL_DATA' not in os.environ:
    os.environ['GDAL_DATA'] = r'/usr/share/gdal/2.1'
from osgeo import gdal,ogr,osr
'GDAL_DATA' in os.environ
```
and of course change the path to your settings.

**Comment by jdmcbr** [comment] 2017-12-10 21:43
Since it seems as though a clean environment addresses this issue, will close this.

**Closed by jdmcbr** 2017-12-10 21:43 UTC
