### ISSUE TITLE
Matplotlib 2.x Tests Fail

### ISSUE THREAD

**Issue by micahcochran** [geopandas/geopandas#455] opened 2017-06-21 21:24 UTC
A couple of the tests in test_plotting.py fail on matplotlib 2.x.

One problem is that `GraphicsContextBase.dashd` no longer exists in matplotlib 2.x.  The [plotting styles have changed from mpl 1.x to 2.x](https://matplotlib.org/users/dflt_style_changes.html#plot).  Here is the commit https://github.com/matplotlib/matplotlib/commit/069785dc4551ad6f4ef7658a9b579a8854054576 that removed `dashd` and added `lines.*_pattern`, which are now called in this manner `mpl.rcParams['lines.dashed_pattern']`.

Some of the color tests are failing.  

Until somebody takes this on, we won't really know what is or is not working in matplotlib 2.x.

**Comment by jorisvandenbossche** [comment] 2017-06-21 21:59
I think this is a duplicate of / related to https://github.com/geopandas/geopandas/issues/278

**Comment by jorisvandenbossche** [comment] 2017-08-05 01:11
Let's keep https://github.com/geopandas/geopandas/issues/278 open for this

**Closed** 2017-08-05 01:10 UTC
