### ISSUE TITLE
BUG: How to generate coloured lines in Linestring

### ISSUE THREAD

**Issue by AdeeshUnnikrishnan** [geopandas/geopandas#2676] opened 2022-12-13 04:42 UTC
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by m-richards** [comment] 2022-12-13 11:13
Hi @AdeeshUnnikrishnan please leave some information in the issue template or describe what the question you have is. Currently there's very little we can do with this besides closing the issue.

**Comment by AdeeshUnnikrishnan** [comment] 2022-12-13 11:25
Hi @m-richards how to use svg under linestring class to get coloured linestring ?
and aslo it gives me the follwoing output when used Linestring.svg()

TypeError: Input must be valid geometry objects: <polyline fill="none" stroke="#ff3333" stroke-width="2.0" points="36.982740093,-121.925481823 36.982740563,-121.925483629 36.982768522,-121.925642971 36.982789156,-121.925808197 36.982790094,-121.925833477 36.982815077,-121.926001724 36.982840003,-121.926167239 36.982864679,-121.926330414 36.982889138,-121.926499488 36.982909976,-121.926671195 36.982933464,-121.926837721 36.982958531,-121.927004951 36.982980356,-121.927172981 36.983002431,-121.92734151 36.983027644,-121.927510192 36.983050409,-121.92767493 36.983072889,-121.927845194 36.983097498,-121.928011116 36.983110887,-121.928160643 36.983132116,-121.92833295 36.983142078,-121.928374142 36.983142546,-121.928375275" opacity="0.8" />

**Comment by martinfleis** [comment] 2022-12-13 15:32
Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug. Otherwise we are not ve to help. Your question is not extremely unclear at the moment.

**Comment by jorisvandenbossche** [comment] 2022-12-29 13:33
I am going to close this issue since there is not enough information to understand what the issue is about. 

@AdeeshUnnikrishnan feel free to still further clarify your question, and we can reopen the issue (note that `.svg()` is not a method of geopandas though, but of shapely)

**Closed** 2022-12-29 13:33 UTC
Labels: needs info
