### ISSUE TITLE
IndexError - None in GeoDataFrame geometry column

### ISSUE THREAD

**Issue by kasperuleman** [geopandas/geopandas#1241] opened 2019-12-23 14:37 UTC
Dear geopandas developers,

While working with a GeoDataFrame with None values in the geometry column, I discovered the following problem: it is not possible to extract rows with (only!) None values in the geometry column. The examples below will fill in on the details.

Goal: given a geodataframe, get all columns where the geometry is None.
IndexError: too many indices for array

Test cases:

import pandas as pd
import geopandas as gpd # version 0.6.1
import shapely.geometry as geom

sample_dict = {'value': [1,2,3,4],
               'geometry': [geom.Point(0,0), None, geom.Point(1,1), None]}

A.
1.  pandas DataFrame can be indexed by its 'geometry' column with some None value

        df = pd.DataFrame(sample_dict)
        df[df.geometry.isnull()]
        Out:
        value geometry
        1      2     None
        3      4     None

2.  geopandas GeoDataFrame cannot be indexed by its 'geometry' column with some None value
        
        df = gpd.GeoDataFrame(sample_dict)
        df[df.geometry.isnull()]
        Out:
        IndexError: too many indices for array
        note: error given in geopandas/array.py (line 752, in total_bounds b[:, 0].min(),  # minx)

3. A Dataframe that has been generated from a GeoDataFrame gives the same error

        df = pd.DataFrame(sample_dict)
        df = pd.DataFrame(gpd.GeoDataFrame(df))
        df[df.geometry.isnull()]
        Out:
        IndexError: too many indices for array
        note: same error as in (2.)

B. 
df = gpd.GeoDataFrame(sample_dict)
1.  Calling iloc on a list on a None geometry works

        df.iloc[1]
        Out:
        value          2
        geometry    None
        Name: 1, dtype: object

        df.iloc[3]
        Out:
        value          4
        geometry    None
        Name: 3, dtype: object

2.  Calling iloc on a list of multiple None geometries does not work

        df.iloc[[1, 3]]
        Out:
        IndexError: too many indices for array
        note: same error as in (2.)

        whereas list of multiple known geometries do work
        df.iloc[[0, 2]]
        Out:
        value                 geometry
        0      1  POINT (0.00000 0.00000)
        2      3  POINT (1.00000 1.00000)

3.  Mixes of known and None geometries do work

        df.iloc[[0,1,3]]
        Out:
        value                 geometry
        0      1  POINT (0.00000 0.00000)
        1      2                     None
        3      4                     None

(First contribution, feedback is welcome.)

**Comment by martinfleis** [comment] 2019-12-23 15:59
Hi @kasperuleman, thank you for the report. However, this seems to be already fixed in 0.6.2. Can you try updating geopandas to the current version?

**Comment by martinfleis** [comment] 2020-01-04 10:50
Closing as the issue is not present in 0.6.2 and master.

**Closed by martinfleis** 2020-01-04 10:50 UTC
