### ISSUE TITLE
Geopandas reading geojson crs incorrectly

### ISSUE THREAD

**Issue by ashnair1** [geopandas/geopandas#1449] opened 2020-05-26 08:09 UTC
I have set my geojson field to have crs as follows:
```
{"type": "FeatureCollection", "crs": {"type": "name", "properties": {"name": "epsg:32613"}}, "features": [....]}
```
However when I read this file using geopandas and check it's crs, it shows it as EPSG 4326 and not 32613 as specified in the geojson

```
x = gpd.read_file('./out_geo/tile_2200-3000.geojson')

x.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
I opened the geojson on QGIS to verify if it was an issue with the geojson and it wasn't the case. Any ideas on why this happens?

**Comment by jdmcbr** [comment] 2020-05-27 04:11
@ashnair1 EPSG 4326 is the CRS for all GeoJSON, per the specifications for GeoJSON. See https://tools.ietf.org/html/rfc7946#page-12 for more information.

**Comment by ashnair1** [comment] 2020-05-27 05:51
Thanks. So what's the common workflow for working with different CRS? In this case, even though the geojson crs is set to 4326, my object coordinates are still with respect to 32613.

**Comment by martinfleis** [comment] 2020-05-27 09:26
The workaround in your case is to assign CRS manually since you know it.

```
x = gpd.read_file('./out_geo/tile_2200-3000.geojson')
x.crs = 32613
```

But even though GeoJSON is 4326 by specification, if I save GeoDataFrame to GeoJSON and read it back, it preserves the initial CRS correctly, so there must be something else happening.

**Comment by ashnair1** [comment] 2020-05-27 10:53
This is indeed what I've been doing (setting crs manually). But I would like the crs to be preserved since the coordinates are w.r.t to 32613. What could cause the CRS to default to 4326 but leave the coordinates the same way? Shouldn't it either change both or neither?

**Comment by martinfleis** [comment] 2020-05-27 11:32
@ashnair1 Can you show the output of `geopandas.show_versions()`? I am unable to reproduce the issue even if manually change geojson to use the CRS specification from the top post. It load the CRS correctly, so there is something working unexpectedly.

**Comment by ashnair1** [comment] 2020-05-27 11:34
```
SYSTEM INFO
-----------
python     : 3.6.9 | packaged by conda-forge | (default, Mar  6 2020, 19:24:21)  [GCC 7.3.0]
executable : /home/ashwin/anaconda3/envs/geo/bin/python
machine    : Linux-4.15.0-88-generic-x86_64-with-debian-stretch-sid

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /home/ashwin/anaconda3/envs/geo/lib/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /home/ashwin/anaconda3/envs/geo/lib/python3.6/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /home/ashwin/anaconda3/envs/geo/lib/python3.6/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.7.0
pandas     : 1.0.3
fiona      : 1.8.13.post1
numpy      : 1.18.4
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.2.1
mapclassify: None
pysal      : None
geopy      : None
psycopg2   : None
```

**Comment by snowman2** [comment] 2020-06-13 21:30
The environment looks invalid. GDAL 2 requires PROJ <= 5. Only GDAL 3 works with PROJ 6+.

**Comment by sahandv** [comment] 2023-09-04 06:31
> The environment looks invalid. GDAL 2 requires PROJ <= 5. Only GDAL 3 works with PROJ 6+.

I know this is pretty late, but as the issue is still open I will respond in case anyone needs it.

I also encountered the issue and resolved it by just creating a new env and NOT installing/re-install GDAL. 
As mentioned by snowman2, this is an issue with GDAL and PROJ versions.

**Comment by martinfleis** [comment] 2023-09-04 10:00
Closing as an installation issue related to pyproj. There's nothing to be done from our side.

**Closed by martinfleis** 2023-09-04 10:00 UTC
