### ISSUE TITLE
wrong country code ISO_3 for France in naturalearth_lowres dataset

### ISSUE THREAD

**Issue by lorifan** [geopandas/geopandas#1041] opened 2019-07-05 07:27 UTC
Not sure this is the right place to mention it, but code iso_3 for France should be 'FRA' not -99.

```
    import geopandas
    path = geopandas.datasets.get_path('naturalearth_lowres')
    world = geopandas.read_file(path)
    world[world['name']=='France'].iso_a3
```

**Comment by jorisvandenbossche** [comment] 2019-07-05 13:48
Could you check if this is also the case in the original data? It's from http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/ 
The script that generates the version bundled with geopandas is in https://github.com/geopandas/geopandas/blob/master/geopandas/datasets/naturalearth_creation.py

If it something in the actual data, you can report issues with that at https://github.com/nvkelso/natural-earth-vector/issues

**Comment by jorisvandenbossche** [comment] 2019-07-05 13:49
Some related discussion: https://github.com/nvkelso/natural-earth-vector/issues/12

**Comment by tommycarstensen** [comment] 2020-03-24 14:49
I have the same issue:

The following iso_a3 codes are incorrect.

`import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world = world[(world.pop_est>0) & (world.name!="Antarctica")]
print(world[world['iso_a3'] == '-99']['name'])
`

21         Norway
43         France
160     N. Cyprus
167    Somaliland
174        Kosovo
Name: name, dtype: object

**Comment by martinfleis** [comment] 2020-03-24 18:12
@tommycarstensen can you check if the same issue has the original source data as mentioned above?

**Comment by tommycarstensen** [comment] 2020-03-24 19:24
@martinfleis I checked and it's a problem with the data source:

```
    import geopandas as gpd
    import requests
    import os
    url = 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_sovereignty.zip'
    url = 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip'
    path = os.path.basename(url)
    with open(path, 'wb') as f:
        f.write(requests.get(url).content)
    world_raw = gpd.read_file("zip://./{}".format(path))
    world_df = world_raw[
        ["POP_EST", "CONTINENT", "NAME", "ISO_A3", "GDP_MD_EST", "geometry"]
        ]
    world_df.columns = world_df.columns.str.lower()

    print(world_df[world_df['iso_a3'] == '-99']['name'])
```

6                     Dhekelia
21                  Somaliland
22                      France
53                      Norway
65                      Kosovo
133        USNB Guantanamo Bay
167                  N. Cyprus
168    Cyprus U.N. Buffer Zone
169            Siachen Glacier
170                   Baikonur
171                   Akrotiri
225          Indian Ocean Ter.
247              Coral Sea Is.
248                Spratly Is.
249              Clipperton I.
251    Ashmore and Cartier Is.
252            Bajo Nuevo Bank
253            Serranilla Bank
254           Scarborough Reef

I noticed this page:
http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/

> Countries distinguish between metropolitan (homeland) and independent and semi-independent portions of sovereign states. If you want to see the dependent overseas regions broken out (like in ISO codes, see France for example), use map units instead.

But France has an ISO alpha3 code equal to the string `-99` in both data sets. I've opted to manually fix it for now.

```
    world.loc[world['name'] == 'France', 'iso_a3'] = 'FRA'
    world.loc[world['name'] == 'Norway', 'iso_a3'] = 'NOR'
    world.loc[world['name'] == 'Somaliland', 'iso_a3'] = 'SOM'
    world.loc[world['name'] == 'Kosovo', 'iso_a3'] = 'RKS'
```

**Comment by jorisvandenbossche** [comment] 2020-03-24 20:19
I don't think we want to deviate from the Natural Earth source. So if you think something is wrong, it's best to open an issue there (https://github.com/nvkelso/natural-earth-vector/issues)

**Comment by dieterwang** [comment] 2020-09-24 13:52
Natural earth provides several ISO3-like codes for admin-0 data (e.g. `SOV_A3, ADM0_A3,...`). They introduced [ISO_A3_EH](https://github.com/nvkelso/natural-earth-vector/issues/237) for this purpose. Wouldn't it make sense to then follow NE and introduce at least one additional column for the "eh" version?

**Comment by martinfleis** [comment] 2020-09-27 19:08
@dieterwang It seems that `ISO_A3_EH` resolves code for France, but not for Norway or Kosovo. There's still an unresolved issue on that https://github.com/nvkelso/natural-earth-vector/issues/284, so I would wait. It looks that there are plans to fix this in 5.0.0 release.

**Comment by asmaier** [comment] 2021-06-03 09:48
It's 2021 and I'm still stumbling about this bug. This is really annoying, because when you want to plot a choropleth world map using `naturalearth_lowres` dataset one has to join the own data with this dataset based on the `iso_a3` column. But this will fail for several countries because of this stupid bug from 2019:

```
[1]: world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
[2]: print(world[world['iso_a3'] == '-99']['name'])
21         Norway
43         France
160     N. Cyprus
167    Somaliland
174        Kosovo
Name: name, dtype: object
```
The workaround at this point of time is:
```
# fix for bug https://github.com/geopandas/geopandas/issues/1041
world.loc[world['name'] == 'France', 'iso_a3'] = 'FRA'
world.loc[world['name'] == 'Norway', 'iso_a3'] = 'NOR'
world.loc[world['name'] == 'N. Cyprus', 'iso_a3'] = 'CYP'
world.loc[world['name'] == 'Somaliland', 'iso_a3'] = 'SOM'
world.loc[world['name'] == 'Kosovo', 'iso_a3'] = 'RKS'
```

I understand that the problem is not caused by geopandas. But it would be very nice if you could fix this issue anyway, so users of geopandas don't have to wait for another two years until https://github.com/nvkelso/natural-earth-vector/issues/284 is resolved.

**Comment by mmaneesh619** [comment] 2021-06-03 11:27
> It's 2021 and I'm still stumbling about this bug. This is really annoying, because when you want to plot a choropleth world map using `naturalearth_lowres` dataset one has to join the own data with this dataset based on the `iso_a3` column. But this will fail for several countries because of this old bug from 2019:
> 
> ```
> [1]: world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
> [2]: print(world[world['iso_a3'] == '-99']['name'])
> 21         Norway
> 43         France
> 160     N. Cyprus
> 167    Somaliland
> 174        Kosovo
> Name: name, dtype: object
> ```
> 
> The workaround at this point of time is:
> 
> ```
> # fix for bug https://github.com/geopandas/geopandas/issues/1041
> world.loc[world['name'] == 'France', 'iso_a3'] = 'FRA'
> world.loc[world['name'] == 'Norway', 'iso_a3'] = 'NOR'
> world.loc[world['name'] == 'N. Cyprus', 'iso_a3'] = 'CYP'
> world.loc[world['name'] == 'Somaliland', 'iso_a3'] = 'SOM'
> world.loc[world['name'] == 'Kosovo', 'iso_a3'] = 'RKS'
> ```
> 
> I understand that the problem is not caused by geopandas. But it would be very nice if you could fix this issue anyway, so users of geopandas don't have to wait for another two years until [nvkelso/natural-earth-vector#284](https://github.com/nvkelso/natural-earth-vector/issues/284) is resolved.

I have been running behind the same for 20 hours. Thanks for posting this. Being a beginner onto this, I was thinking myself gone wrong somewhere.

**Comment by cpbl** [comment] 2021-10-09 22:41
Still a problem in pandas 1.3.1+,  even though https://github.com/nvkelso/natural-earth-vector/issues/284 was fixed  in August 2021.
Workaround remains:

```
# fix for bug https://github.com/geopandas/geopandas/issues/1041
world.loc[world['name'] == 'France', 'iso_a3'] = 'FRA'
world.loc[world['name'] == 'Norway', 'iso_a3'] = 'NOR'
world.loc[world['name'] == 'N. Cyprus', 'iso_a3'] = 'CYP'
world.loc[world['name'] == 'Somaliland', 'iso_a3'] = 'SOM'
world.loc[world['name'] == 'Kosovo', 'iso_a3'] = 'RKS'

```

**Comment by martinfleis** [comment] 2021-10-10 10:51
It was fixed but the fix is not released yet.

**Comment by martinfleis** [comment] 2021-12-08 17:05
A new version of the Natural Earth datasets has been released https://github.com/nvkelso/natural-earth-vector/releases/tag/v5.0.0. Hopefully, this will fix all the issues in our data once we update our built-in file.

**Comment by martinfleis** [comment] 2022-02-19 23:28
Hmm, so not this issue is not fixed in NaturalEarth 5.0.0. So I would suggest we update our built-in dataset and fix this manually while doing that.

**Comment by rraymondgh** [comment] 2022-04-21 09:34
Have dug into this with NaturalEarth 5.0.1.  I see two options to resolve
1. update some country codes
```
# not ideal - fix some country codes
mask = world_raw["ISO_A3"].eq("-99") & world_raw["TYPE"].isin(['Sovereign country', 'Country'])
world_raw.loc[mask, "ISO_A3"] = world_raw.loc[mask, "ADM0_A3"]
```
2. include **ADM0_A3** column as well in dataset that **geopandas** distributes

Would like input from members on preferred option and I'll generate a PR to update distributed sample geometry.

Two other points
1.  **GDP_MD_EST** has been renamed **GDP_MD**.  I would recommend that it is renamed for backward compatibility with test cases.
2. comment in **naturalearth_creation.py** is wrong, using 110m dataset not 10m dataset.


### diff option 1 ###
```
world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))

world.loc[:, ["continent", "name", "iso_a3", "geometry"]].compare(
    world_df.loc[:, ["continent", "name", "iso_a3", "geometry"]]
)
```
|     | ('name', 'self')   | ('name', 'other')   |   ('iso_a3', 'self') | ('iso_a3', 'other')   |
|----:|:-------------------|:--------------------|---------------------:|:----------------------|
|  21 | nan                | nan                 |                  -99 | NOR                   |
|  43 | nan                | nan                 |                  -99 | FRA                   |
| 160 | nan                | nan                 |                  -99 | CYN                   |
| 171 | Macedonia          | North Macedonia     |                  nan | nan                   |
| 174 | nan                | nan                 |                  -99 | KOS                   |


### full code with rename ###
```
import geopandas as gpd
from pathlib import Path
import requests
import urllib

url = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip"
f = Path.cwd().joinpath("../geopandas/geopandas/datasets").joinpath(urllib.parse.urlparse(url).path.split("/")[-1])

if not f.exists():
    r = requests.get(url, stream=True, headers={"User-Agent": "XY"})
    with open(f, "wb") as fd:
        for chunk in r.iter_content(chunk_size=128):
            fd.write(chunk)


# assumes zipfile from naturalearthdata was downloaded to current directory
world_raw = gpd.read_file(f)

# not ideal - fix some country codes
mask = world_raw["ISO_A3"].eq("-99") & world_raw["TYPE"].isin(['Sovereign country', 'Country'])
world_raw.loc[mask, "ISO_A3"] = world_raw.loc[mask, "ADM0_A3"]

# subsets columns of interest for geopandas examples
world_df = world_raw[
    ["POP_EST", "CONTINENT", "NAME", "ISO_A3", "GDP_MD", "geometry"]
].rename(columns={"GDP_MD":"GDP_MD_EST"}) # column has changed name...
world_df.columns = world_df.columns.str.lower()
```

**Comment by martinfleis** [comment] 2022-04-21 09:40
> include ADM0_A3 column as well in dataset that geopandas distributes

That does not have these issues? I wouldn't include both. The point of `naturalearth_lowres` being included in geopandas is to have a toy example dataset, not to provide a canonical map of the world.

I'd be personally fine with manual renaming to resolve the issues pointed out in this issue and document that there is this small deviation from the original data. 

> GDP_MD_EST has been renamed GDP_MD. I would recommend that it is renamed for backward compatibility with test cases.
> comment in naturalearth_creation.py is wrong, using 110m dataset not 10m dataset.

Yes and yes.

**Comment by rraymondgh** [comment] 2022-04-21 10:06
> That does not have these issues? I wouldn't include both. 
It's all in data definition.... but to your point simplest is to override for general simple use in way I have indicated.

> I'd be personally fine with manual renaming to resolve the issues pointed out in this issue and document that there is this small deviation from the original data.

I'll go ahead with this and generate a PR

**Closed** 2022-06-05 16:32 UTC
