### ISSUE TITLE
BUG: PyGEOS sjoin AttributeError

### ISSUE THREAD

**Issue by jnsplt** [geopandas/geopandas#1778] opened 2021-01-15 21:31 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

Sorry, you have to download a country shapes file first - I'm too much of a newbie with geopandas to spare you that:
[https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip) 

Then put the file `ne_10m_admin_0_countries.shp` into your working dir.

You also have to have pyGEOS installed.

#### Code Sample, a copy-pastable example

```python
from shapely.geometry import Point
import geopandas as gpd

gpd.options.use_pygeos = True

country_boundaries = gpd.read_file("ne_10m_admin_0_countries.shp")
locations = gpd.GeoDataFrame(
    crs='epsg:4326',
    geometry=[Point(xy) for xy in zip([17.38712, -115.48232], [-30.41875, 35.16875])])

lookups = gpd.sjoin(
    locations, country_boundaries[["CONTINENT", "geometry"]],
    how='left', op='intersects') 
print(lookups)

```

#### Problem description

An exception is raised with pyGEOS enabled. When setting `gpd.options.use_pygeos = False` everything runs as expected.

<details>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-def0be580067> in <module>
      6 lookups = gpd.sjoin(
      7     locations, country_boundaries[["CONTINENT", "geometry"]],
----> 8     how='left', op='intersects')
      9 print(lookups)

~/miniconda3/envs/mt_geoload/lib/python3.7/site-packages/geopandas/tools/sjoin.py in sjoin(left_df, right_df, how, op, lsuffix, rsuffix)
     86             # keep them the same
     87             predicate = op
---> 88             sindex = right_df.sindex
     89             input_geoms = left_df.geometry
     90 

~/miniconda3/envs/mt_geoload/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5458             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5459                 return self[name]
-> 5460             return object.__getattribute__(self, name)
   5461 
   5462     def __setattr__(self, name: str, value) -> None:

~/miniconda3/envs/mt_geoload/lib/python3.7/site-packages/geopandas/base.py in sindex(self)
    591     def sindex(self):
    592         if not self._sindex_generated:
--> 593             self._generate_sindex()
    594         return self._sindex
    595 

~/miniconda3/envs/mt_geoload/lib/python3.7/site-packages/geopandas/base.py in _generate_sindex(self)
     98         sindex_cls = get_sindex_class()
     99         if sindex_cls is not None:
--> 100             _sindex = sindex_cls(self.geometry)
    101             if not _sindex.is_empty:
    102                 self._sindex = _sindex

~/miniconda3/envs/mt_geoload/lib/python3.7/site-packages/geopandas/sindex.py in __init__(self, geometry)
    314             super().__init__(non_empty)
    315             # store geometries, including empty geometries for user access
--> 316             self.geometries = geometry.values.data.copy()
    317 
    318         def query(self, geometry, predicate=None, sort=False):

AttributeError: can't set attribute
```

</details>

#### Expected Output

```
                      geometry  index_right      CONTINENT
0   POINT (17.38712 -30.41875)           37         Africa
1  POINT (-115.48232 35.16875)          153  North America
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.7 (default, Mar 23 2020, 22:36:06)  [GCC 7.3.0]
executable : /home/jonas/miniconda3/envs/mt_geoload/bin/python
machine    : Linux-5.4.0-60-generic-x86_64-with-debian-bullseye-sid

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /home/jonas/miniconda3/envs/mt_geoload/lib/libgeos_c.so
GDAL       : 3.0.2
GDAL data dir: /home/jonas/miniconda3/envs/mt_geoload/share/gdal
PROJ       : 6.2.1
PROJ data dir: /home/jonas/miniconda3/envs/mt_geoload/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.0
fiona      : 1.8.13.post1
numpy      : 1.19.2
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.2
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None

additional info on pyGEOS from conda list
--------------------------
pygeos                    0.6              py37hb106bac_1    conda-forge

</details>

**Comment by martinfleis** [comment] 2021-01-16 18:37
Hi, thanks for the report. I am not able to reproduce the issue with the latest versions of GeoPandas and pygeos. Can you try updating pygeos to 0.8 and let us know if that changed anything?

**Comment by bubalis** [comment] 2021-01-20 01:37
I get the same issue with pygeos v 0.6. 

When I update to pygeos v 0.8, I get the following warning: 

"UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.8.1-CAPI-1.13.3). Conversions between both will be slow."

pytho 3.7
geopandas 0.8.1
shapely 1.7.1

**Comment by martinfleis** [comment] 2021-01-23 12:20
How did you install packages? Can you show an output of `conda list`? My sense is that this is an installation error, I cannot replicate in any of my environments/systems.

**Comment by jorisvandenbossche** [comment] 2021-01-24 20:18
pygeos 0.6 is certainly too old, we are using newer functionalities, and that's the reason an AttributeError is raised if your version is not recent enough. We should avoid users getting such hard to understand error though, and do a bit more checking of the installed version. I quickly put up https://github.com/geopandas/geopandas/pull/1792

**Comment by tomrod-pcci** [comment] 2021-01-26 17:25
I hit this with a recent install too, installed geopandas and dependencies from conda.

**Comment by tomrod-pcci** [comment] 2021-01-26 17:28
The issue is magnified since installation on Windows is a bear without conda.

**Comment by martinfleis** [comment] 2021-01-26 17:42
@tomrod-pcci which version pygeos do you have? Can you post the output of `geopandas.show_versions()` and `conda list`?

**Comment by Imanflow** [comment] 2021-01-27 20:52
I wanted to test this, and code runs as expected. I installed pygeos and geopandas with pip in a new conda environment. 

SYSTEM INFO
-----------
python     : 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable : /media/imanol/anaconda3/envs/pygeos_test/bin/python
machine    : Linux-5.4.0-64-generic-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: /media/imanol/anaconda3/envs/pygeos_test/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.2.0
PROJ data dir: /media/imanol/anaconda3/envs/pygeos_test/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.2
pandas     : 1.2.1
fiona      : 1.8.18
numpy      : 1.19.5
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.0.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
None

But what I don't understand is the output as if I had no GEOS installed.

**Comment by tomrod-pcci** [comment] 2021-01-28 13:59
####Geopandas show_versions():

```console
SYSTEM INFO
-----------
python     : 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\[snipped]\AppData\Local\Continuum\anaconda3\envs\[snipped]\python.exe
machine    : Windows-10-10.0.16299-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Users\[snipped]\AppData\Local\Continuum\anaconda3\envs\[snipped]\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.1
fiona      : 1.8.13.post1
numpy      : 1.19.2
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.2
mapclassify: 2.4.2
geopy      : 2.1.0
psycopg2   : 2.8.4 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
```

#### Conda packages

```console
# packages in environment at C:\Users\[snipped]\AppData\Local\Continuum\anaconda3\envs\[snipped]:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
attrs                     20.3.0             pyhd3eb1b0_0
azure-core                1.10.0                   pypi_0    pypi
azure-storage-blob        12.7.1                   pypi_0    pypi
azure-storage-file-datalake 12.2.2                   pypi_0    pypi
azure-storage-file-share  12.4.1                   pypi_0    pypi
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
bzip2                     1.0.8                he774522_0
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cartopy                   0.17.0          py37hde43876_1009    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cffi                      1.14.4           py37hd8e9650_1    conda-forge
cfitsio                   3.470                he774522_6
chardet                   4.0.0            py37h03978a9_1    conda-forge
click                     7.1.2              pyhd3eb1b0_0
click-plugins             1.1.1                      py_0
cligj                     0.7.1            py37haa95532_0
colorama                  0.4.4              pyhd3eb1b0_0
coloredlogs               15.0             py37haa95532_0
contextily                1.0.1                      py_0    conda-forge
cryptography              3.3.1            py37hd8e9650_1    conda-forge
curl                      7.67.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
decorator                 4.4.2                      py_0
descartes                 1.1.0                      py_4    conda-forge
et_xmlfile                1.0.1                   py_1001
expat                     2.2.10               h33f27b4_2
fiona                     1.8.13.post1     py37hd760492_0
freetype                  2.10.4               hd328e21_0
freexl                    1.0.6                h2bbff1b_0
gdal                      3.0.2            py37hdf43c64_0
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.8.1                      py_0
geoplot                   0.4.1                      py_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.8.0                h33f27b4_0
geotiff                   1.5.1                h5770a2b_1
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
humanfriendly             9.1              py37haa95532_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2020.2                      254
ipython                   7.19.0           py37hd4e2768_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
isodate                   0.6.0                    pypi_0    pypi
jdcal                     1.4.1                      py_0
jedi                      0.17.2           py37haa95532_1
joblib                    1.0.0              pyhd3eb1b0_0
jpeg                      9b                   hb83a4c4_2
kealib                    1.4.7                h07cbb95_6
kiwisolver                1.3.0            py37hd77b12b_0
krb5                      1.16.4               hc04afaa_0
libblas                   3.8.0                    20_mkl    conda-forge
libboost                  1.67.0               hd9e427e_4
libcblas                  3.8.0                    20_mkl    conda-forge
libcurl                   7.67.0               h2a8f88b_0
libgdal                   3.0.2                h1155b67_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             4.3.0a               h7ffb84d_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.10               hb89e7f3_3
lz4-c                     1.8.1.2              h2fa13f4_0
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mapclassify               2.4.2              pyhd8ed1ab_0    conda-forge
matplotlib                3.3.2                haa95532_0
matplotlib-base           3.3.2            py37hba9282a_0
mercantile                1.1.6              pyh9f0ad1d_0    conda-forge
mkl                       2020.2                      256
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.2.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
msrest                    0.6.21                   pypi_0    pypi
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.2           py37hadc3359_0
numpy-base                1.19.2           py37ha3acd2a_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0
openjpeg                  2.3.0                h5ec785f_1
openpyxl                  3.0.6              pyhd3eb1b0_0
openssl                   1.1.1i               h8ffe710_0    conda-forge
owslib                    0.22.0             pyhd8ed1ab_0    conda-forge
pandas                    1.2.1            py37hf11a4ad_0
parso                     0.7.0                      py_0
pcre                      8.44                 ha925a31_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.0            py37h4fa10fc_0
pip                       20.3.3           py37haa95532_0
postgresql                11.2                 h3235a2c_0
proj                      6.2.1                h9f7ef89_0
prompt-toolkit            3.0.8                      py_0
psycopg2                  2.8.4            py37h7a1dbc1_0
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygeos                    0.6              py37h64833c9_1    conda-forge
pygments                  2.7.4              pyhd3eb1b0_0
pykdtree                  1.3.4            py37hda49f71_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyhd3eb1b0_0
pyproj                    2.6.1.post1      py37hcfa1391_1
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py37h03978a9_3    conda-forge
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd3eb1b0_0
pyyaml                    5.4.1            py37hcc03f2d_0    conda-forge
qt                        5.9.7            vc14h73c81de_0
rasterio                  1.1.2            py37h2617b1b_0    conda-forge
reportlab                 3.5.60           py37h52c0f85_1
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rtree                     0.9.4            py37h21ff451_1
scikit-learn              0.24.1           py37heb15398_0    conda-forge
scipy                     1.5.2            py37h9439919_0
seaborn                   0.11.1             pyhd3eb1b0_0
setuptools                52.0.0           py37haa95532_0
shapely                   1.7.1            py37h210f175_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
smartystreets-python-sdk  4.7.2                    pypi_0    pypi
snuggs                    1.4.7                      py_0    conda-forge
sqlalchemy                1.3.21           py37h2bbff1b_0
sqlite                    3.33.0               h2a8f88b_0
structlog                 20.2.0             pyhd3deb0d_0    conda-forge
tbb                       2018.0.5             he980bc4_0
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    1.6.3                h7b000aa_0
tk                        8.6.10               he774522_0
tornado                   6.1              py37h2bbff1b_0
traitlets                 5.0.5                      py_0
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2                      py37_0
xerces-c                  3.2.3                ha925a31_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.3.7                      py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7                h508b16e_0
```

**Comment by tomrod-pcci** [comment] 2021-01-28 14:01
I am not sure a safe way to update `pygeos` to a more recent version without losing `geopandas` functionality, as windows machine installs for this are quite difficult.

**Comment by tomrod-pcci** [comment] 2021-01-28 14:37
example code for where I'm running into issues:

```python
import geopandas as gpd
import pandas as pd

df = pd.DataFrame.from_dict(
	{'Rec1': [32.80, -96.60, 'a'],
	'Rec2': [32.78, -97.01, 'b']},
	orient='index'
)
df.columns = ['latitude','longitude','DummyExample']
shape = gpd.read_file("/path/to/any/shp_or_geojson.shp").to_crs('epsg:4269')
gdf = gpd.GeoDataFrame(
        df, 
        geometry=gpd.points_from_xy(df.longitude, df.latitude),
        crs = 'epsg:4269'
    ) #Note -- this also adds a geometry column to original df, perhaps separate bug
gjoin = gpd.sjoin(shape, gdf, how='left')
```

Traceback

```console
In [1]: import geopandas as gpd
   ...: import pandas as pd
   ...: 
   ...: df = pd.DataFrame.from_dict(
   ...: ^I{'Rec1': [32.80, -96.60, 'a'],
   ...: ^I'Rec2': [32.78, -97.01, 'b']},
   ...: ^Iorient='index'
   ...: )
   ...: df.columns = ['latitude','longitude','DummyExample']
   ...: shape = gpd.read_file("[snipped]").to_crs('epsg:4269')
   ...: gdf = gpd.GeoDataFrame(
   ...:         df,
   ...:         geometry=gpd.points_from_xy(df.longitude, df.latitude),
   ...:         crs = 'epsg:4269'
   ...:     )
   ...: gjoin = gpd.sjoin(shape, gdf, how='left')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5792c8288f32> in <module>
     15         crs = 'epsg:4269'
     16     )
---> 17 gjoin = gpd.sjoin(shape, gdf, how='left')

~\AppData\Local\Continuum\anaconda3\envs\covid_b_map_2\lib\site-packages\geopandas\tools\sjoin.py in sjoin(left_df, right_df, how, op, lsuffix, rsuffix)
     86             # keep them the same
     87             predicate = op
---> 88             sindex = right_df.sindex
     89             input_geoms = left_df.geometry
     90

~\AppData\Local\Continuum\anaconda3\envs\covid_b_map_2\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5460             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5461                 return self[name]
-> 5462             return object.__getattribute__(self, name)
   5463
   5464     def __setattr__(self, name: str, value) -> None:

~\AppData\Local\Continuum\anaconda3\envs\covid_b_map_2\lib\site-packages\geopandas\base.py in sindex(self)
    591     def sindex(self):
    592         if not self._sindex_generated:
--> 593             self._generate_sindex()
    594         return self._sindex
    595

~\AppData\Local\Continuum\anaconda3\envs\covid_b_map_2\lib\site-packages\geopandas\base.py in _generate_sindex(self)
     98         sindex_cls = get_sindex_class()
     99         if sindex_cls is not None:
--> 100             _sindex = sindex_cls(self.geometry)
    101             if not _sindex.is_empty:
    102                 self._sindex = _sindex

~\AppData\Local\Continuum\anaconda3\envs\covid_b_map_2\lib\site-packages\geopandas\sindex.py in __init__(self, geometry)
    314             super().__init__(non_empty)
    315             # store geometries, including empty geometries for user access
--> 316             self.geometries = geometry.values.data.copy()
    317
    318         def query(self, geometry, predicate=None, sort=False):

AttributeError: can't set attribute
```

**Comment by tomrod-pcci** [comment] 2021-01-28 14:38
Note that, after creating the `gdf` object, the original `df` object now has a geometry attribute:

```python
In [2]: df
Out[2]: 
      latitude  longitude DummyExample                    geometry
Rec1     32.80     -96.60            a  POINT (-96.60000 32.80000)
Rec2     32.78     -97.01            b  POINT (-97.01000 32.78000)
```

Not sure if related or separate bug

**Comment by tomrod-pcci** [comment] 2021-01-28 14:45
Last comment on this for the moment: geometry types of the `shape` object above are `Polygon` or `MultiPolygon` -- was never an issue before this particular set of libraries.  I tested with `shape` subsets of only polygon or multipolygon, same outcome.

**Comment by martinfleis** [comment] 2021-01-28 15:52
@tomrod-pcci You have pygeos 0.6 in your environment. You need at least 0.8 (note that with 0.9 you'll need geopandas 0.8.2).

> Note that, after creating the gdf object, the original df object now has a geometry attribute:

That is a know bug #1179.

Also, one general observation. You have mixed conda channels in your environment, i.e. shapely coming from `defaults` while pygeos from `conda-forge`. I would strongly advise against that and sticking to one source (ideally conda-forge). Mixing channels can cause compatibility issues.

**Comment by martinfleis** [comment] 2021-01-28 15:53
All who reported this issue had older pygeos than required. Updating resolves the issue, so I will close this report.

**Closed by martinfleis** 2021-01-28 15:53 UTC
Labels: bug, needs info, needs triage

**Comment by tomrod-pcci** [comment] 2021-01-28 15:55
Updating which -- pygeos or geopandas? When I update pygeos it no longer works with geopandas provided by conda, and installing outside of conda on Windows 10 is a mostly undocumented "hear thar be dragons" process.

**Comment by martinfleis** [comment] 2021-01-28 15:59
Try the following to get both to the latest versions

```
conda install -c conda-forge geopandas=0.8.2 pygeos=0.9
```

**Comment by tomrod-pcci** [comment] 2021-01-28 16:05
I am greatly appreciative of your support! Will test out.

**Comment by tomrod-pcci** [comment] 2021-01-29 01:04
Returning and reporting -- rebuilt the virtual environment with a fresh install. Python 3.7 was too dated to support the above solution. Python 3.9.1 + conda on Windows 10 works well. 

Thanks again for your assistance.
