### ISSUE TITLE
GeoPandas '0.9.0' does not read correctly the CRS in Python 3.7

### ISSUE THREAD

**Issue by ran-pelta** [geopandas/geopandas#1882] opened 2021-03-16 14:58 UTC
I have this polygon as a GeoJSON file:

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32614" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 385692.315535633417312, 2665734.629486501216888 ], [ 385752.565762493002694, 2665907.707511680666357 ], [ 385973.504760747193359, 2665845.335410861764103 ], [ 385920.972954970493447, 2665669.763593637850136 ], [ 385692.315535633417312, 2665734.629486501216888 ] ] ], [ [ [ 385733.187279019562993, 2665913.178351240698248 ], [ 385672.945492088387255, 2665740.124590761493891 ], [ 385462.083911215595435, 2665799.946275424677879 ], [ 385510.970917687052861, 2665975.915454667527229 ], [ 385733.187279019562993, 2665913.178351240698248 ] ] ], [ [ [ 385491.626872348948382, 2665981.376948713324964 ], [ 385442.7467252817587, 2665805.432456693146378 ], [ 385198.318574909644667, 2665874.781979747582227 ], [ 385254.933825746877119, 2666048.206011556554586 ], [ 385491.626872348948382, 2665981.376948713324964 ] ] ], [ [ [ 385235.574371829337906, 2666053.67226471286267 ], [ 385178.967076495871879, 2665880.272615892346948 ], [ 384942.6304983261507, 2665947.331439384259284 ], [ 385002.294641724787652, 2666119.542462015058845 ], [ 385235.574371829337906, 2666053.67226471286267 ] ] ], [ [ [ 384982.918213087075856, 2666125.013909137807786 ], [ 384923.262473451148253, 2665952.827161924447864 ], [ 384712.73012637719512, 2666012.568419008050114 ], [ 384763.264541121840011, 2666187.041012389585376 ], [ 384982.918213087075856, 2666125.013909137807786 ] ] ] ] } }
]
}
```

As you can see the EPSG:32614.

When I read this file with GeoPandas on Python 3.6 (geopandas version '0.8.1') I get the correct CRS:

```
df = gpd.read_file(p)
df.crs
>>>
   <Projected CRS: EPSG:32614>
Name: WGS 84 / UTM zone 14N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: World - N hemisphere - 102°W to 96°W - by country
- bounds: (-102.0, 0.0, -96.0, 84.0)
Coordinate Operation:
- name: UTM zone 14N
- method: Transverse Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```

However, in Python 3.7 (geopandas version '0.9.0') I get the wrong CRS:

```
df = gpd.read_file(p)
df.crs
>>>
<Geographic 2D CRS: EPSG:4326>
    Name: WGS 84
    Axis Info [ellipsoidal]:
    - Lat[north]: Geodetic latitude (degree)
    - Lon[east]: Geodetic longitude (degree)
    Area of Use:
    - name: World.
    - bounds: (-180.0, -90.0, 180.0, 90.0)
    Datum: World Geodetic System 1984
    - Ellipsoid: WGS 84
    - Prime Meridian: Greenwich
```

**Comment by jorisvandenbossche** [comment] 2021-03-17 15:13
@ran-pelta can you show the result of `geopandas.show_version()` in both cases?  
(to check whether the difference might be related to a difference in GDAL / fiona version)

**Comment by ran-pelta** [comment] 2021-03-17 16:28
I get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9c98348337b8> in <module>
----> 1 gpd.show_version()

AttributeError: module 'geopandas' has no attribute 'show_version'
```

**Comment by akrherz** [comment] 2021-03-17 16:42
Try `gpd.show_versions()` (plural)

**Comment by ran-pelta** [comment] 2021-03-18 06:35
@akrherz , thanks

**Python 3.6**

```
SYSTEM INFO
-----------
python     : 3.6.11 (default, Aug  5 2020, 19:41:03) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\ran\Anaconda3\envs\main\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: None
PROJ       : 7.0.0
PROJ data dir: C:\Users\ran\Anaconda3\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.0
fiona      : 1.8.9.post2
numpy      : 1.18.5
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.1
mapclassify: None
geopy      : 2.0.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
```

**Python 3.7**

```
SYSTEM INFO
-----------
python     : 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\ran\Anaconda3\envs\poi37\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.2
GDAL data dir: None
PROJ       : 7.2.1
PROJ data dir: C:\Users\ran\Anaconda3\envs\poi37\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.3
fiona      : 1.8.18
numpy      : 1.20.1
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
```

**Comment by jorisvandenbossche** [comment] 2021-03-18 13:33
@ran-pelta how did you install the packages in the Python 3.7 environment? 
Because it seems that `pyproj` is not installed with conda, since it's using embedded PROJ data, and not from an installed PROJ

Further, to see whether it's just related to fiona, or actually to geopandas, could you show the output of the following snippet in both environments? (with the file name you use substituted of course)

```
import fiona
fiona.open("test_crs.geojson").meta
```

**Comment by akrherz** [comment] 2021-03-18 13:38
Ignorant peanut gallery here, but I thought `crs` information within GeoJSON is not permitted since the specification was formalized by [IETF[(https://tools.ietf.org/html/rfc7946).  It is always now assumed to be `EPSG:4326` and any such information is now ignored.

**Comment by ran-pelta** [comment] 2021-03-18 13:48
@jorisvandenbossche  - I created the Python 3.6 and 3.7 virtual envs in anaconda. 
I don't remember if I used `pip` or `conda `to install `pyproj` in the 3.6 but in 3.7 I used pip and installed it from a file called - `pyproj-3.0.1-cp37-cp37m-win_amd64.whl`.

About what you asked:
**Python 3.6**

```
import fiona
fiona.open(r"C:\Users\ran\Desktop\test.geojson").meta
>>>
{'driver': 'GeoJSON',
 'schema': {'properties': OrderedDict(), 'geometry': 'MultiPolygon'},
 'crs': {'init': 'epsg:32614'},
 'crs_wkt': 'PROJCS["WGS 84 / UTM zone 14N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-99],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32614"]]'}
```


**Python 3.7**


```
import fiona
fiona.open(r"C:\Users\ran\Desktop\test.geojson").meta
>>>
{'driver': 'GeoJSON',
 'schema': {'properties': OrderedDict(), 'geometry': 'MultiPolygon'},
 'crs': {'init': 'epsg:4326'},
 'crs_wkt': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'}
```

**Comment by ran-pelta** [comment] 2021-03-18 13:50
@akrherz  what do you mean by now in "such information is now ignored"?  I mean, now since when?

**Comment by johnflavin** [comment] 2021-04-04 13:57
@ran-pelta It appears the packages you have installed into your 3.7 environment can’t work together consistently. This is likely because of the mixed conda/pip installation. The best practice (by which I mean “easiest way to get a working set of dependencies”) is to install everything using conda from the conda-forge channel. See the installation instructions at https://geopandas.org/getting_started.html

The reason for this is that the various python package dependencies of geopandas (like fiona, pyproj, shapely, etc.) rely on C or C++ libraries (GEOS, GDAL, PROJ). When you use conda, it installs those C libraries into a common location and all the python packages point to them in a consistent way. When you install from wheels, they will typically have the C dependencies they need bundled inside. That can lead to interoperability issues of the versions the have packaged are different than or incompatible with the requirements of some of the other packages in the dependency ecosystem. It is possible to make a consistent environment with all wheels, or maybe using pip and building from source, though it is more difficult than with all conda packages. And a mixed environment installed partially using conda and partially using pip is all but guaranteed to have compatibility issues. (Note that this doesn’t apply to everything in the python world, as a huge number of packages don’t need any C libraries and will happily work with mixed conda/pip environments. The geospatial stack required by geopandas is more delicate in that regard than most other environments.)

With regard to CRS in GeoJSON:

CRS information is not officially part of the GeoJSON spec anymore. The [Coordinate Reference System section](https://tools.ietf.org/html/rfc7946#section-4) of the spec says
> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) datum, with longitude and latitude units of decimal degrees.

But saying it is “not permitted” is not correct. They know CRS information is often included, and that’s ok.
> However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

**Comment by ran-pelta** [comment] 2021-04-05 06:40
@johnflavin  I understand, thank you

**Comment by martinfleis** [comment] 2021-04-08 14:54
Based on the output of `fiona.open(r"C:\Users\ran\Desktop\test.geojson").meta` above, it is clear that the issue boils down to `fiona` returning different CRS in each environment. That is likely caused by an incorrect installation (esp. links to its C dependencies) precisely explained by @johnflavin.

I will close this issue as related to installation of `fiona`. There's nothing we can do about it on GeoPandas side and it does not even seem to be a bug in fiona itself.

**Closed by martinfleis** 2021-04-08 14:54 UTC
Labels: bug, needs triage
