### ISSUE TITLE
 gcc: error: geopandas/vectorized.c: No such file or directory

### ISSUE THREAD

**Issue by KarenChen9999** [geopandas/geopandas#679] opened 2018-02-22 03:52 UTC
Hi,

When I install geopandas-cython using command "pip install git+https://github.com/geopandas/geopandas.git@geopandas-cython", I got following error messages. I check where my gcc sitting at, which is located at /bin/gcc

    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/apps/anaconda3/envs/dask/lib/python3.6/site-packages/numpy/core/include -I/apps/anaconda3/envs/dask/include -I/apps/anaconda3/envs/dask/include/python3.6m -c geopandas/vectorized.c -o build/temp.linux-x86_64-3.6/geopandas/vectorized.o
    gcc: error: geopandas/vectorized.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 4

    ----------------------------------------
  ```
Rolling back uninstall of geopandas
Command "/apps/anaconda3/envs/dask/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-l361rj89-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wjrlaj3w-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-l361rj89-build/

```
I have installed gcc by running
`sudo assist yum gcc`

Can anyone suggest what I can do to resolve this issue?

**Comment by jorisvandenbossche** [comment] 2018-03-16 13:08
@KarenChen9999 sorry for the slow reply, but thanks for the report and for trying out the cython branch.






To try out, you can also install from conda-forge (although of course we still need to solve the problem): 

```
conda install --channel conda-forge/label/dev geopandas
```

**Comment by jorisvandenbossche** [comment] 2018-03-16 13:33
So for the actual problem. I get a very similar one locally if I try to reproduce this. One of the problems is I think that the `setup.py` is not yet really working with pip (because you need to specify `--with-cython` for now). This is something we need to fix, and discussed a bit in https://github.com/geopandas/geopandas/issues/473. Also related: https://github.com/geopandas/geopandas/pull/586

You can pass additional options to `pip install`, so the following should work:

```
pip install git+https://github.com/geopandas/geopandas.git@geopandas-cython --install-option="--with-cython"
```

**Comment by avnovikov** [comment] 2018-03-22 09:30
Just an addition to this one (although I may have screwed my environment). After installation with cython flags I receive following message when trying to import geopandas
'''
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b9161ee55771> in <module>()
      5 from copy import copy
      6 
----> 7 import geopandas as gpd
      8 import numpy as np
      9 import pandas as pd

/anaconda3/envs/mariquant/lib/python3.6/site-packages/geopandas/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function
      2 
----> 3 from geopandas.geoseries import GeoSeries
      4 from geopandas.geodataframe import GeoDataFrame, concat
      5 

/anaconda3/envs/mariquant/lib/python3.6/site-packages/geopandas/geoseries.py in <module>()
     15 from shapely.ops import transform
     16 
---> 17 from .base import GeoPandasBase, _series_unary_op, _CoordinateIndexer
     18 from .vectorized import from_shapely, GeometryArray
     19 from ._block import GeometryBlock

/anaconda3/envs/mariquant/lib/python3.6/site-packages/geopandas/base.py in <module>()
     13 import shapely.affinity as affinity
     14 
---> 15 from . import vectorized
     16 
     17 try:

ImportError: cannot import name 'vectorized'
'''

**Comment by martinfleis** [comment] 2022-02-19 22:55
The Cython branch is no longer under active development. Closing the issue as outdated.

**Closed by martinfleis** 2022-02-19 22:55 UTC
