### ISSUE TITLE
geopandas version >=0.6 breaks append method

### ISSUE THREAD

**Issue by kirkhansen** [geopandas/geopandas#1239] opened 2019-12-19 15:59 UTC
Prior to 0.6, the following code works.
```python
import geopandas as gpd                                                                    
df = gpd.GeoDataFrame()
df.append(gpd.GeoSeries(), ignore_index=True)
```
```                                                                                                                      
Empty DataFrame
Columns: []
Index: [0]
```
0.6 and up
```python
import geopandas as gpd                                         
df = gpd.GeoDataFrame()
df.append(gpd.GeoSeries(), ignore_index=True)
```
```                                                                                                                            
---------------------------------------------------------------------------
AttributeError                            
Traceback (most recent call last)
<ipython-input-3-44a6946466ae> in <module>
----> 1 df.append(gpd.GeoSeries(), ignore_index=True)

~/.pyenv/versions/3.7.3/envs/plot-generator/lib/python3.7/site-packages/pandas/core/frame.py in append(self, other, ignore_index, verify_integrity, sort)
   7114             other = other.reindex(combined_columns, copy=False)
   7115             other = DataFrame(
-> 7116                 other.values.reshape((1, len(other))),
   7117                 index=index,
   7118                 columns=combined_columns,

AttributeError: 'GeometryArray' object has no attribute 'reshape'
```

related issue #1230 
Looks like the pandas.api.extensions.ExtensionArray is missing some features.

**Comment by martinfleis** [comment] 2020-05-24 15:55
I can't reproduce the issue on master anymore. Closing as fixed. Thank you for the report!

**Closed by martinfleis** 2020-05-24 15:55 UTC
Labels: bug
