### ISSUE TITLE
BUG: `GeoDataFrame` constructor will mutate the inputting data

### ISSUE THREAD

**Issue by Zeroto521** [geopandas/geopandas#2518] opened 2022-08-09 09:31 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import geopandas as gpd

df = pd.DataFrame({"x": [122, 100], "y": [55, 1]})
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(
        df['x'],
        df['y'],
    ),
)
print(df)  # df was changed
#      x   y                    geometry
# 0  122  55  POINT (122.00000 55.00000)
# 1  100   1   POINT (100.00000 1.00000)
print(gdf)
#      x   y                    geometry
# 0  122  55  POINT (122.00000 55.00000)
# 1  100   1   POINT (100.00000 1.00000)
```

#### Problem description

`GeoDataFrame` constructor will mutate the inputting data `df`.
This behavior happened in geopandas 0.10.2 and 0.11.0.

#### Expected Output

```python
df = pd.DataFrame({"x": [122, 100], "y": [55, 1]})
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(
        df['x'],
        df['y'],
    ),
)
print(df)
#      x   y
# 0  122  55
# 1  100   1
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\GISUNI\mambaforge\envs\dtoolkit-dev\python.exe
machine    : Windows-10-10.0.19044-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.5.0
GDAL data dir: None
PROJ       : 9.0.0
PROJ data dir: C:\Users\GISUNI\mambaforge\envs\dtoolkit-dev\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.1
numpy      : 1.22.4
pandas     : 1.4.2
pyproj     : 3.3.1
shapely    : 1.8.2
fiona      : 1.8.21
geoalchemy2: None
geopy      : 2.2.0
matplotlib : 3.5.2
mapclassify: 2.4.3
pygeos     : 0.12.0
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.0

</details>

**Comment by martinfleis** [comment] 2022-08-09 09:42
Thanks for the report. Thought this is a duplicate of #1179.

**Closed by martinfleis** 2022-08-09 09:42 UTC
Labels: bug, needs triage
