### ISSUE TITLE
Intersects and Touches Difference

### ISSUE THREAD

**Issue by christianfong** [geopandas/geopandas#1131] opened 2019-09-19 01:02 UTC
I'm getting the following odd behavior (for which I am unfortunately unable to provide sample code because I'm working with proprietary data that I don't own).

I have a GeoSereis called x.  When I call x.touches(x.iloc[7]), I get:
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

However, when I call x.intersection(x.iloc[7]), I getL
128     (LINESTRING (-93.671622 31.393237, -93.671494 ...
1162                                                   ()
1168                                                   ()
1326                                                   ()
1835                                                   ()
1836                                                   ()
2484                                                   ()
2749    POLYGON ((-92.07901 31.058236, -92.080393 31.0...
3605                                                   ()
dtype: object

I find that odd.  If they intersect by a linestring, doesn't that mean they touch?  When I plot them, they clearly touch and don't overlap except at the boundary.

**Comment by jorisvandenbossche** [comment] 2019-09-19 06:50
The definition of touches is:

> a touches b: they have at least one point in common, but their interiors do not intersect. 

(from https://en.wikipedia.org/wiki/DE-9IM)

So for the one where the intersection is a polygon, I think is to be expected that they don't touch. For where the intersection is a MultiLineString, you can indeed expect that they touch, but I suppose it still depends on the actual data.

You can always do `x.relate(x.iloc[7])` to get more insight in the details of the relationship between both.

If you can, I would say try to reproduce this with data that you can share (maybe a small subset, shift and scale the coordinates so it is not recognizable, ...), otherwise it will be hard to help.

**Comment by martinfleis** [comment] 2019-10-13 18:56
As @jorisvandenbossche explained, this is (probably, as we don't have the data) expected behaviour, so I am closing this for now.

**Closed by martinfleis** 2019-10-13 18:56 UTC

**Comment by nmcdtu** [comment] 2024-04-15 16:09
Dear @jorisvandenbossche , I want to color maps with 2 differing colors for any 2 adjacent polygons, hence I would like to use `relate`. Because by some unclear reason, my data did not work 100% correctly with `touches`, `intersects`, `crosses`, `contains` .

Could you please tell me what is the DE-9IM code for 2 polygons which share at least 2 common points (including their boundaries)?


> The definition of touches is:
> 
> > a touches b: they have at least one point in common, but their interiors do not intersect.
> 
> (from https://en.wikipedia.org/wiki/DE-9IM)
> 
> So for the one where the intersection is a polygon, I think is to be expected that they don't touch. For where the intersection is a MultiLineString, you can indeed expect that they touch, but I suppose it still depends on the actual data.
> 
> You can always do `x.relate(x.iloc[7])` to get more insight in the details of the relationship between both.

**Comment by martinfleis** [comment] 2024-04-15 16:18
@nmcdtu not directly answering the question but this may solve your problem https://pysal.org/mapclassify/notebooks/05_Greedy_coloring.html

**Comment by nmcdtu** [comment] 2024-04-16 12:03
@martinfleis : Thank you, it is interesting!

I found out that the problem is in fact with my data, no issues with `geopandas`.
For example, here are 2 of my polygons:

```
{ "type": "Feature", 
"properties": { "Code": "NL012_OFF", "Study Zone": "NL00_OFF", "code_color": "#cfcf4d" }, 
"geometry": { "type": "Polygon", 
"coordinates": [ [ [ 2.763332999999814, 54.38 ], [ 2.806504653244628, 54.457610213637942 ], 
[ 4.271934664386891, 55.36136449189928 ], [ 4.333333000000116, 55.333333 ], [ 4.999999999999829, 55.0 ], 
[ 5.000000000000166, 54.619999999999841 ], [ 6.000000000000232, 54.186667 ],
[ 6.020203261492064, 54.151629912976539 ], [ 4.50745759276106, 54.108491749610998 ],
[ 4.04410917056157, 53.479281494380501 ], [ 4.044088289612739, 53.479232656809565 ],
[ 2.902578687309123, 53.852383056356338 ], [ 2.866667, 53.963332999999878 ], [ 2.763332999999814, 54.38 ] ] ] } }
```

and 
```
{ "type": "Feature",
"properties": { "Code": "DE013_OFF", "Study Zone": "DE00_OFF", "code_color": "#9b6144" },
"geometry": { "type": "MultiPolygon",
"coordinates": [ [ [ [ 4.271934664386914, 55.361364491899288 ], [ 4.27521, 55.36332 ], 
[ 4.728734952732368, 55.420024812955972 ], [ 4.75, 55.404167 ], [ 5.015232999999729, 55.301942 ],
[ 5.150000000000171, 55.250000000000114 ], [ 5.4033329999997, 55.249999999999893 ],
[ 5.75, 55.511194 ], [ 6.419049951246758, 55.390153034316796 ], [ 6.41739281081132, 55.387500761168504 ],
[ 5.405342509277642, 54.446448453340274 ], [ 5.000000000000271, 54.620000000000125 ],
[ 5.0, 55.0 ], [ 4.333333000000255, 55.333333 ], [ 4.271934664386914, 55.361364491899288 ] ] ],
[ [ [ 3.370278000000136, 55.765 ], [ 3.399001604782389, 55.832652820149029 ],
[ 3.37039371522075, 55.764949150128992 ], [ 3.370278000000136, 55.765 ] ] ] ] } }
```

An edge in the 1st polygon
`[ 4.271934664386891, 55.36136449189928 ], [ 4.333333000000116, 55.333333 ]`
is super close to another edge in the 2nd polygon
`[ 4.333333000000255, 55.333333 ], [ 4.271934664386914, 55.361364491899288 ]`.

Hence, if we show them on the map, it looks like they are adjacent, but in fact there is still some tiny gap. Of course, one can pre-process the data by rounding to some precision.

Besides that, I am still curious if there might be some function or some trick in `geopandas` to deal with such case?
Thank you!

**Comment by martinfleis** [comment] 2024-04-17 11:00
@nmcdtu you can try to derive so called [fuzzy contiguity](https://pysal.org/libpysal/generated/libpysal.weights.fuzzy_contiguity.html#libpysal.weights.fuzzy_contiguity) and pass that as `sw` to the `greedy` function. If I understand the question.

**Comment by nmcdtu** [comment] 2024-04-18 08:50
> @nmcdtu you can try to derive so called [fuzzy contiguity](https://pysal.org/libpysal/generated/libpysal.weights.fuzzy_contiguity.html#libpysal.weights.fuzzy_contiguity) and pass that as `sw` to the `greedy` function. If I understand the question.

Thank you, it would be very useful for me! I will test it.

> The second case is similar to the first, only the resultant edges do not intersect but are “close”.
