### ISSUE TITLE
Seems like outputs for some plots in docs were incorrectly submitted

### ISSUE THREAD

**Issue by kuanb** [geopandas/geopandas#466] opened 2017-07-13 23:23 UTC
Looks like a few of the later plots on this page (http://geopandas.org/set_operations.html) were cancelled during their creation and those keyboard interrupts were instead submitted.

See below image:

![image](https://user-images.githubusercontent.com/6053396/28191816-767254c6-67e7-11e7-8ee9-37288c5e27de.png)

**Comment by jdmcbr** [comment] 2017-08-08 05:41
Closing as duplicate of #345.

**Closed by jdmcbr** 2017-08-08 05:41 UTC
