### ISSUE TITLE
Cannot write csv in 0.6.0 if geometry contains multipolygon

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1145] opened 2019-10-07 21:08 UTC
I have encountered an error in 0.6.0 when writing a GeoDataFrame to csv if the geometry has a MultiPolygon shape.

This worked in 0.5.1:
```
$ conda create -n gpd051 python=3.6 geopandas=0.5.1
<conda output>
$ conda activate gpd051
(gpd051) $ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:07:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.wkt import loads
>>> import geopandas as gpd
>>> geom_str = 'MULTIPOLYGON (((1 0, 1 1, 0 1, 0 0, 1 0)), ((3 0, 3 1, 2 1, 2 0, 3 0)))'
>>> geom = loads(geom_str)
>>> gdf = gpd.GeoDataFrame(geometry=[geom])
>>> gdf.to_csv()
',geometry\n0,"MULTIPOLYGON (((1 0, 1 1, 0 1, 0 0, 1 0)), ((3 0, 3 1, 2 1, 2 0, 3 0)))"\n'
```

But the same steps fail in 0.6.0 with `ValueError: setting an array element with a sequence`:
```
$ conda create -n gpd060 python=3.6 geopandas=0.6.0
<conda output>
$ conda activate gpd060
(gpd060) $ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:07:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.wkt import loads
>>> import geopandas as gpd
>>> geom_str = 'MULTIPOLYGON (((1 0, 1 1, 0 1, 0 0, 1 0)), ((3 0, 3 1, 2 1, 2 0, 3 0)))'
>>> geom = loads(geom_str)
>>> gdf = gpd.GeoDataFrame(geometry=[geom])
>>> gdf.to_csv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john.flavin/anaconda3/envs/gpd060/lib/python3.6/site-packages/pandas/core/generic.py", line 3228, in to_csv
    formatter.save()
  File "/Users/john.flavin/anaconda3/envs/gpd060/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 202, in save
    self._save()
  File "/Users/john.flavin/anaconda3/envs/gpd060/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 324, in _save
    self._save_chunk(start_i, end_i)
  File "/Users/john.flavin/anaconda3/envs/gpd060/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 340, in _save_chunk
    quoting=self.quoting,
  File "/Users/john.flavin/anaconda3/envs/gpd060/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 760, in to_native_types
    values = values.astype(str)
ValueError: setting an array element with a sequence
```

I have a hypothesis about what's going on. (I don't know much about the internals of how GeoDataFrames are represented, so take this with a grain of salt.) The source of the exception is this block in `pandas/core/internals/blocks.py`:
```
        if not self.is_object and not quoting:
            values = values.astype(str)
        else:
            values = np.array(values, dtype="object")
```
My guess is that since the `geometry` column used to be an `object` type, `not self.is_object` would have been `False` and `values = values.astype(str)` would not have been evaluated. But now `geometry` is of type `geometry` so `not self.is_object` is `True` and we get the error.

**Comment by jorisvandenbossche** [comment] 2019-10-07 22:10
@johnflavin thanks a lot for the report and the detailed reproducible example!

Your guess seems to be right. It's the `astype(str)` that is failing, which in the end might be a numpy issue, but its due to a change in geopandas that we now run into that issue.

I am not directly sure if this can be solved in geopandas itself. Will take a look on the pandas side.

**Comment by jorisvandenbossche** [comment] 2019-10-07 22:18
Another failure related to this that we *can* solve on the geopandas side is direct `astype` on a geodataframe/series:

```
In [62]: gdf.geometry.astype(str)
...
~/scipy/geopandas/geopandas/array.py in astype(self, dtype, copy)
    866             else:
    867                 return self
--> 868         return np.array(self, dtype=dtype, copy=copy)
    869 
    870     def isna(self):

ValueError: setting an array element with a sequence
```

Here, we should be special case converting to string and do the conversion ourselves (to not bump into the numpy issue).

The numpy issue is specific to the "Multi" aspect. With a plain point/line/polygon, you don't have this problem:

```
In [83]: p = Point(1, 1) 

In [84]: np.array([p], dtype=object).astype(str) 
Out[84]: array(['POINT (1 1)'], dtype='<U11')
```

but with MultiPoint, you run into the same as above:

```
In [85]: a = np.empty(1, dtype=object)  

In [86]: a[:] = [MultiPoint([p, p])]   

In [87]: a.astype(str)   
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-87-db38302b5f9a> in <module>
----> 1 a.astype(str)

ValueError: setting an array element with a sequence
```

**Comment by johnflavin** [comment] 2019-10-08 15:58
Thanks for the quick fix! 🚀

**Comment by jorisvandenbossche** [comment] 2019-10-11 07:06
OK, the `astype(str)` is fixed on master; the PR on the geopandas side will also be merged shortly.

I will probably try to do a 0.6.1 bugfix release shortly to include the geopandas fix. But so closing this issue.

**Closed by jorisvandenbossche** 2019-10-11 07:06 UTC
Labels: bug

**Comment by jorisvandenbossche** [comment] 2019-10-12 08:42
@johnflavin FYI 0.6.1 is released
