### ISSUE TITLE
Dropping a column in a geodataframe returns a regular dataframe

### ISSUE THREAD

**Issue by ccamara** [geopandas/geopandas#1349] opened 2020-04-01 08:42 UTC
Provided a `geopandas`' geodataframe, whenever I drop a column like I do with a regular pandas dataframe (see code below), it gets transformed into a regular dataframe, and hence, losing its geospatial properties. Is there any way to prevent that?

    In [23]:type(gdf)
    Out [23]: geopandas.geodataframe.GeoDataFrame
    
    In [24]: gdf = gdf.drop(columns=['tmp_category'])
    
    In [25]: type(gdf)
    Out [26]: pandas.core.frame.DataFrame

**Comment by martinfleis** [comment] 2020-04-01 08:44
I can't reproduce the issue. Which version of `geopandas` do you use? Can you provide reproducible example?

**Comment by ccamara** [comment] 2020-04-01 09:17
Thanks for your reply, @martinfleis . While I was preparing the following reproducible code I realised it worked just fine, so apparently my problem has to be somewhere else. 

Just for the sake of documentation, I am copying the code and output using geopandas 0.7.0:

```python

# %%
import geopandas as gpd
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/mapcolabora/osm_imports_preparations/master/imports/2020_03_pharmacies_cvalenciana/data/processed/pharmacies_cval.csv')
# Convert dataframe into a GeoDataframe.
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df.lon, df.lat))

print(type(gdf))
```
out: `<class 'geopandas.geodataframe.GeoDataFrame'>`

```python
#%% Dropping column
gdf = gdf.drop(columns=['lat'])

print(type(gdf))
```
out: `<class 'geopandas.geodataframe.GeoDataFrame'>`

Sorry for the inconvenience

**Comment by ccamara** [comment] 2020-04-01 09:31
Yes, I can confirm that the geopandas gets converted in one of the many manipulations I have made before, more likely somewhere here:

```python

# Fix uppercase.
gdf['name'] = gdf['name'].str.title()

# Addresses' cleanup.
gdf['addr:full'] = gdf['addr:full'].str.title()
# Split address.
gdf['addr:street'], gdf['addr:housenumber'], gdf['addr:unit'] = gdf['addr:full'].str.split(',', 2).str
gdf['addr:street'].replace({'C/': 'Carrer'}, inplace=True, regex=True)


# Filter out entries without category
gdf = gdf.dropna(subset=['tmp_category'])

# Remove pharmacies, because they have already been imported
gdf = gdf[gdf.tmp_category != 'Salut|Farmàcies||']

# Create amenity column according to `CATEGORIA`
# Health
gdf.loc[gdf.tmp_category.str.contains("Centres d'atenció primària"), 'amenity' ] = 'clinic'


```

**Comment by martinfleis** [comment] 2020-04-01 09:34
@ccamara That should not happen. Can you figure out where that happens? Or provide example so we can debug and fix it?

**Comment by ccamara** [comment] 2020-04-01 13:18
Thanks for reopening and help me to debug the problem: the whole code where I am finding the problem is here: https://github.com/mapcolabora/osm_imports_preparations/blob/master/imports/2020_03_equipaments_catalunya/equipaments_cat.ipynb I will debug it an provide a shorter code later.

**Comment by martinfleis** [comment] 2020-04-01 13:24
@ccamara I haven't tried it, but this is suspicious as we do not have a control over it. You can see in `gdf.head(10)` right after, that gdf no longer contain geometry.

```
# Selects and renames fields according to CSV parser.
gdf = osmi_dg.csv_parser(gdf, CSV_PARSER)
```

**Comment by ccamara** [comment] 2020-04-01 13:38
Oh, I see. It is very likely, indeed. As a python newbie who comes from R universe, I expected a similar behaviour as to a `sf`'s spatial dataframes, which store data and geometry in different places. I understand that this is not the case in geopandas. If so, you are definitely right, as I conciously removed `geometry` column in that function.

**Comment by martinfleis** [comment] 2020-04-01 13:43
GeoDataFrame stores geometry within the same DataFrame as every other data. GeoDataFrame without geometry column is not considered as valid, hence it may be returned as DataFrame in some occasions. I believe that resolves the issue, so I am closing it now. Next time there's no need to open an issue, we are monitoring StackOverflow, so I also seen your question there as well. SO is a better place for this kind of debugging.

**Closed by martinfleis** 2020-04-01 13:43 UTC

**Comment by ccamara** [comment] 2020-04-01 13:49
Thank you for your explanations and sorry of the inconvenience. It is good to know about geopandas behaviour (it may seem obvious for you, but it wasn't for me due to the fact that is not what I have been experiencing in R) as well as how you prefer to deal with issues and questions (which largely differ from project to project).

Oh, and by the way, thanks for developing and maintaining (I've been greatly surprised on how fast and nicely you have dealt with this issue) geopandas, which I realise I will be using on a daily basis for my python projects.

**Comment by captionsecond-rate** [comment] 2025-02-05 22:24
Grasp this https://pythoner.space/questions/utilize-the-dropna-function-on-a-specific-subset-to-tidy-up-the-data explanation
