### ISSUE TITLE
BUG: `GeoDataFrame.from*` methods should use class constructor

### ISSUE THREAD

**Issue by NickLucche** [geopandas/geopandas#2432] opened 2022-05-18 09:48 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
class MyGeoDataFrame(gpd.GeoDataFrame):
    pass 
a = MyGeoDataFrame.from_dict({'geometry': [Point(0,0)], 'value': [1]})
type(a)
# >> geopandas.geodataframe.GeoDataFrame
```

#### Problem description

As title, `GeoDataFrame.from*` methods should use the class constructor since they're class methods, so that implementations sub-classing `GeoDataFrame` work as intended. 

#### Expected Output
`MyGeoDataFrame`

#### Output of ``geopandas.show_versions()``

SYSTEM INFO
-----------
python     : 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0]
executable : /home/nick/miniconda3/bin/python
machine    : Linux-5.13.0-41-generic-x86_64-with-glibc2.34

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: /home/nick/miniconda3/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 7.2.1
PROJ data dir: /home/nick/miniconda3/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.0
pandas     : 1.2.5
fiona      : 1.8.18
numpy      : 1.20.3
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 3.4.3
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 6.0.1
pygeos     : 0.10.2

</details>

**Comment by m-richards** [comment] 2022-05-19 03:12
Hi @NickLucche thanks for pointing this out. I'm going to close this issue as a duplicate of #1355 but I'll keep your PR open (but as you'll see from there, supporting subclassing will potentially take a fair bit more work than just altering the class constructor). 

But please do engage with that issue, particularly https://github.com/geopandas/geopandas/issues/1355#issuecomment-669977993 about you might use subclassing.

**Closed by m-richards** 2022-05-19 03:12 UTC
Labels: bug, needs triage
